BEGIN;

UPDATE public.services
SET catalog_position = NULL
WHERE active = TRUE;

UPDATE public.services
SET active = FALSE,
    catalog_position = NULL
WHERE id IN ('svc-yono-bonus-51', 'svc-all-yono-games', 'svc-rani-slots', 'svc-yono-arcade', 'svc-yono-all-games', 'svc-yono-game', 'svc-yono-app', 'svc-new-yono-app', 'svc-all-rummy-apps', 'svc-diva-ace', 'svc-diva-lucky', 'svc-diva-king', 'svc-diva-x', 'svc-diva-top', 'svc-divavip', 'svc-diva-game', 'svc-diva-slots', 'svc-diva-777', 'svc-diva-2026', 'svc-download-yono-rummy', 'svc-download-rummy-365', 'svc-koko-slots', 'svc-all-yono-slots');

WITH positions(id, service_name, catalog_position) AS (
  VALUES
  ('svc-joy-rummy','Joy Rummy',1),
('svc-ind-rummy','IND Rummy',2),
('svc-inr-rummy','INR Rummy',3),
('svc-rumble-rummy','Rumble Rummy',4),
('svc-bingo-101','Bingo 101',5),
('svc-spin-101','Spin 101',6),
('svc-diwa-top','Diwa Top',7),
('svc-jaiho-slots','Jaiho Slots',8),
('svc-rummy-91','Rummy 91',9),
('svc-max-rummy','Max Rummy',10),
('svc-gold-rummy','Gold Rummy',11),
('svc-win-rummy','Win Rummy',12),
('svc-diwa-x','Diwa X',13),
('svc-jaiho-rummy','Jaiho Rummy',14),
('svc-jaiho-91','Jaiho 91',15),
('svc-diwa-win','Diwa Win',16),
('svc-maha-games','Maha Games',17),
('svc-jaiho-777-vip','Jaiho 777 VIP',18),
('svc-rummy-888','Rummy 888',19),
('svc-dhan-game','Dhan Game',20),
('svc-diwa-game','Diwa Game',21),
('svc-diwa-vip','Diwa VIP',22),
('svc-ind-club','IND Club',23),
('svc-diwa-slots','Diwa Slots',24),
('svc-diwa-777','DIWA 777',25),
('svc-spin-crush','Spin Crush',26),
('svc-spin-winner','Spin Winner',27),
('svc-spin-gold','Spin Gold',28),
('svc-slots-winner','Slots Winner',29),
('svc-rummy-ludo','Rummy Ludo',30),
('svc-jaiho-spin','Jaiho Spin',31),
('svc-yono-777','Yono 777',32),
('svc-rummy-77','Rummy 77',33),
('svc-777-game','777 Game',34),
('svc-club-inr','Club INR',35),
('svc-winzo-rummy','Winzo Rummy',36),
('svc-rummy-app','Rummy App',37),
('svc-ever-777','Ever 777',38),
('svc-inr-slots','INR Slots',39),
('svc-good-slots','Good Slots',40),
('svc-boss-rummy','Boss Rummy',41),
('svc-hindi-777','Hindi 777',42),
('svc-yn-777','YN 777',43),
('svc-yes-spin','Yes Spin',44),
('svc-ok-rummy','OK Rummy',45),
('svc-love-rummy','Love Rummy',46),
('svc-share-slots','Share Slots',47),
('svc-hi-rummy','Hi Rummy',48),
('svc-jaiho-win','Jaiho Win',49),
('svc-goa-spin','Goa Spin',50),
('svc-slots-spin','Slots Spin',51),
('svc-mqm-bet','MQM Bet',52),
('svc-saga-slots','Saga Slots',53),
('svc-rummy-yono','Rummy Yono',54),
('svc-abc-rummy','ABC Rummy',55),
('svc-jaiho-arcade','Jaiho Arcade',56),
('svc-neta-vip','Neta VIP',57),
('svc-mwm-bet','MWM Bet',58),
('svc-en-365','EN 365',59),
('svc-101z-app','101Z App',60),
('svc-rummy-365','Rummy 365',61),
('svc-ind-bingo','IND Bingo',62),
('svc-my-777','My 777',63),
('svc-bet-213-slots','Bet 213 Slots',64),
('svc-gogo-rummy','GoGo Rummy',65),
('svc-789-jackpot','789 Jackpot',66),
('svc-mdm-bet','MDM Bet',67),
('svc-spin-lucky','Spin Lucky',68),
('svc-ind-slots','IND Slots',69),
('svc-mkm-bet','MKM Bet',70),
('svc-yono-maha-games','Yono Maha Games',71),
('svc-game-rummy','Game Rummy',72),
('svc-mbm-bet','MBM Bet',73),
('svc-jaiho-777','Jaiho 777',74),
('svc-top-rummy','TOP Rummy',75),
('svc-spin-777','Spin 777',76),
('svc-567-slots','567 Slots',77),
('svc-yono-vip','Yono VIP',78),
('svc-yono-slots','Yono Slots',79),
('svc-yono-rummy','Yono Rummy',80),
('svc-yono-games','Yono Games',81),
('svc-money-rummy','Money Rummy',82),
('svc-yn-rummy','YN Rummy',83),
('svc-yoyo-slots','Yoyo Slots',84),
('svc-svip-777','SVIP 777',85),
('svc-rummy-zip','Rummy Zip',86),
('svc-diwa-lucky','Diwa Lucky',87),
('svc-diwa-ace','Diwa Ace',88),
('svc-diwa-king','Diwa King',89),
('svc-diwa-play','Diwa Play',90),
('svc-diwa-bet','Diwa Bet',91),
('svc-diwa-spin','Diwa Spin',92),
('svc-diwa-rummy','Diwa Rummy',93),
('svc-diwa-club','Diwa Club',94),
('svc-diwa-91','Diwa 91',95),
('svc-diwa-gold','Diwa Gold',96),
('svc-jeet-spin','Jeet Spin',97),
('svc-all-diwa-apps','All Diwa Apps',98),
('svc-pp-777','PP 777',99),
('svc-holy-rummy','Holy Rummy',100),
('svc-teen-patti-master','Teen Patti Master',101),
('svc-ind-vip','Ind Vip',102),
('svc-rumble-rummy-77','Rumble Rummy 77',103),
('svc-yono-rumble-rummy','Yono Rumble Rummy',104),
('svc-bolly-game','Bolly Game',105),
('svc-t989','T989',106),
('svc-rummy-mate','Rummy Mate',107),
('svc-rummy-gold','Rummy GOLD',108),
('svc-tycoon','Tycoon',109),
('svc-k9','K9',110),
('svc-mmy','MMY',111),
('svc-bdg-game','BDG Game',112),
('svc-new-66-lotry','NEW 66 lotry',113),
('svc-ww9','Ww9',114),
('svc-goplay11','Goplay11',115),
('svc-win-03','Win 03',116),
('svc-woho-game','Woho Game',117),
('svc-yono-slot','Yono Slot',118),
('svc-come11','Come11',119),
('svc-kaliwins','KaliWins',120),
('svc-rummy-holly','RUMMY HOLLY',121),
('svc-rummy-nabob','rummy nabob',122),
('svc-rummy-ola','RUMMY OLA',123),
('svc-jai-ho-slots','JAI HO SLOTS',124),
('svc-slot-spin','Slot Spin',125),
('svc-teen-patti-gold','Teen Patti Gold',126),
('svc-rummy-wealth','Rummy Wealth',127),
('svc-rummy-modern','Rummy Modern',128),
('svc-rummy-all-app','Rummy All App',129),
('svc-ak777','AK777',130),
('svc-rummy-ares','Rummy Ares',131),
('svc-11-winner-apk','11 Winner APK',132),
('svc-all-rummy-app','All Rummy App',133),
('svc-rummy-new-app','Rummy New App',134),
('svc-colour-trading','Colour Trading',135),
('svc-prosafe-bet','Prosafe Bet',136),
('svc-msm-bet','MSM Bet',137),
('svc-365-jeet','365 Jeet',138),
('svc-rk-ludo','RK Ludo',139),
('svc-gogo-anime','Gogo Anime',140),
('svc-spin-yono','Spin Yono',141),
('svc-game-3f','Game 3f',142),
('svc-download-svip','Download Svip',143),
('svc-kal-win','KAL WIN',144),
('svc-rummy-sultan','Rummy Sultan',145),
('svc-new-rummy-app','New Rummy App',146),
('svc-1a-game','1a Game',147),
('svc-8-game-app','8 Game App',148),
('svc-slots-777','Slots 777',149),
('svc-slot-guru','Slot Guru',150),
('svc-rummy-black','Rummy Black',151),
('svc-teenpatti-happy','TeenPatti Happy',152),
('svc-rummy-master','Rummy Master',153),
('svc-yono-rummy-2026','Yono Rummy 2026',154),
('svc-all-yono-apk','All Yono Apk',155),
('svc-casino-game','CASINO GAME',156),
('svc-yono-games-list','Yono Games List',157),
('svc-777-rummy','777 Rummy',158),
('svc-rummy-vip-apk','Rummy Vip APK',159),
('svc-download-rummy-ludo','Download Rummy Ludo',160),
('svc-crush-spin','Crush Spin',161),
('svc-abc-vip','ABC VIP',162),
('svc-rummy-333','Rummy 333',163),
('svc-best-yono-app','Best Yono App',164),
('svc-best-yono','Best Yono',165),
('svc-pop-slots','POP Slots',166),
('svc-download-lcg-bet','DOWNLOAD LCG BET',167),
('svc-3-patti-master','3 Patti Master',168),
('svc-teen-patti-bliss','Teen Patti Bliss',169),
('svc-navo-slots','Navo Slots',170),
('svc-jaiclub-game','Jaiclub GAME',171),
('svc-sxripl-game','SXRIPL GAME',172),
('svc-rummy-loot','Rummy Loot',173),
('svc-all-vv5-game','ALL VV5 GAME',174),
('svc-crown-rummy','Crown Rummy',175),
('svc-teenpatti-bazaar','Teenpatti Bazaar',176),
('svc-5177-win','5177 Win',177),
('svc-yono-arcarde','Yono Arcarde',178),
('svc-rummy-good','Rummy Good',179),
('svc-bet-11','Bet 11',180),
('svc-ayuipl-game','AYUIPL GAME',181),
('svc-rummy-777','Rummy 777',182),
('svc-raja-game-download','Raja Game Download',183),
('svc-yono-yoyo-slots','Yono Yoyo Slots',184),
('svc-gg9-android-app','Gg9 Android App',185),
('svc-frenzy-winner','Frenzy Winner',186),
('svc-en-365-games','En 365 Games',187),
('svc-9game-apk','9Game Apk',188),
('svc-diwa-slot','Diwa Slot',189),
('svc-namaste-teenpatti-apk','Namaste Teenpatti Apk',190),
('svc-3-patti-hot','3 Patti Hot',191),
('svc-21-game-download','21 Game Download',192),
('svc-rummy-grand','Rummy Grand',193)
)
UPDATE public.services AS s
SET active = TRUE,
    catalog_position = p.catalog_position
FROM positions AS p
WHERE s.id = p.id;

UPDATE public.services
SET active = FALSE,
    catalog_position = NULL
WHERE active = TRUE
  AND catalog_position IS NULL;

INSERT INTO schema_migrations(version)
VALUES ('034_service_catalog_duplicate_cleanup')
ON CONFLICT DO NOTHING;

COMMIT;
