import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getNotifications, markAllNotificationsRead, markNotificationRead } from '../api/notifications';
import { getWallet } from '../api/wallet';
import { createRecharge } from '../api/recharges';
import { getSessions, revokeSession, updateProfile, changePassword, issueRecoveryCode, logoutAll } from '../api/account';
import { createSupportTicket, getSupportTickets, replySupportTicket } from '../api/support';
import type { Notification } from '../api/types';
import type { AdminRecharge } from '../api/types';
import { getAdminRecharges, reviewAdminRecharge, getAdminPaymentReconciliation, updatePaymentSettings, getAdminLedger } from '../api/admin-payments';
import { useSessionStore } from '../state/session';
import { Icon } from './customer-ui-shared';

function WalletPage(){
 const client=useQueryClient();
 const q=useQuery({queryKey:['wallet'],queryFn:getWallet,refetchInterval:10000,refetchOnReconnect:true});
 const [amount,setAmount]=useState('500');const [utr,setUtr]=useState('');const [customerPaidAt,setCustomerPaidAt]=useState('');const [error,setError]=useState<string|null>(null);
 const [sent,setSent]=useState(false);const [submittedRechargeId,setSubmittedRechargeId]=useState<string|null>(null);const [upiCopied,setUpiCopied]=useState(false);const [paymentStarted,setPaymentStarted]=useState(false);
 const [filter,setFilter]=useState<'all'|'credit'|'debit'>('all');const [rechargeFilter,setRechargeFilter]=useState<'all'|'pending'|'review'|'approved'|'rejected'>('all');const [detail,setDetail]=useState<string|null>(null);

 function localDateTimeNow(){const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16);}
 const recharge=useMutation({
  mutationFn:()=>createRecharge(Number(amount),utr.trim(),customerPaidAt?new Date(customerPaidAt).toISOString():undefined),
  onSuccess:async(created)=>{setError(null);setSent(true);setSubmittedRechargeId(created.id);setUtr('');setCustomerPaidAt('');setPaymentStarted(false);await Promise.all([q.refetch(),client.invalidateQueries({queryKey:['notifications']})])},
  onError:e=>setError(e instanceof Error?e.message:'Recharge could not be submitted')
 });
 const ledger=q.data?.ledger??[];const recharges=q.data?.recharges??[];const settings=q.data?.paymentSettings;
 const filteredLedger=ledger.filter(x=>filter==='all'||x.type===filter);
 const pendingRechargeRows=recharges.filter(r=>String(r.status).toLowerCase()==='pending');
 const pendingRecharges=pendingRechargeRows.length;
 const pendingAmountPaise=pendingRechargeRows.reduce((sum,r)=>sum+(r.amountPaise||0),0);
 const statusMeta=(status:string)=>{const value=status.replace(/_/g,' ').toLowerCase();if(['verified','approved','credited','completed','success','successful'].includes(value))return {label:'Verified',tone:'success'};if(['rejected','failed','declined','cancelled','canceled'].includes(value))return {label:'Rejected',tone:'danger'};if(['flagged','manual review','under review'].includes(value))return {label:'Review',tone:'review'};return {label:value||'Pending',tone:'pending'}};
 const selectedRecharge=detail?recharges.find(r=>r.id===detail):null;
 const visibleRecharges=recharges.filter(r=>{const status=String(r.status||'').toLowerCase();if(rechargeFilter==='all')return true;if(rechargeFilter==='pending')return status==='pending'&&!r.flaggedAt;if(rechargeFilter==='review')return Boolean(r.flaggedAt);if(rechargeFilter==='approved')return ['approved','verified','completed','success','successful'].includes(status);if(rechargeFilter==='rejected')return ['rejected','failed','declined','cancelled','canceled'].includes(status);return true;});
 const upiIntent=q.data?.upiId?'upi://pay?pa='+encodeURIComponent(q.data.upiId)+'&pn='+encodeURIComponent(settings?.merchantName||'INBOX9')+'&am='+encodeURIComponent((Number(amount||0)).toFixed(2))+'&cu=INR&tn='+encodeURIComponent('INBOX9 Wallet Recharge'):null;
 async function copyUpi(){if(!q.data?.upiId)return;try{await navigator.clipboard.writeText(q.data.upiId);setUpiCopied(true);window.setTimeout(()=>setUpiCopied(false),1400)}catch{setError('Copy is not available in this browser.')}}
 function startPayment(){setSent(false);setSubmittedRechargeId(null);setError(null);setPaymentStarted(true);if(!customerPaidAt)setCustomerPaidAt(localDateTimeNow())}
 function resetRechargeForm(){setSent(false);setSubmittedRechargeId(null);setError(null);setUtr('');setCustomerPaidAt('');setPaymentStarted(false)}
 function openUpi(){if(!upiIntent)return;startPayment();window.location.href=upiIntent}
 return <section className="page-section wallet-page">
  <div className="catalog-heading wallet-heading"><div><span className="catalog-eyebrow">WALLET</span><h1>Wallet</h1><p>Recharge securely, track verification, and keep every wallet movement in one place.</p></div><span className="catalog-chip">INR</span></div>
  <div className="wallet-overview">
   <div className="wallet-overview-main wallet-summary-cell wallet-balance-cell"><span>Available balance</span><strong>₹{((q.data?.balancePaise??0)/100).toFixed(2)}</strong><small>{q.isPending?'Refreshing wallet…':q.isError?'Balance unavailable':pendingRecharges?pendingRecharges+' recharge'+(pendingRecharges===1?' is':'s are')+' awaiting verification':'No recharge is awaiting verification'}</small></div>
   <div className="wallet-stat-grid">
    <div className="wallet-summary-cell"><span>Pending amount</span><strong>₹{(pendingAmountPaise/100).toFixed(2)}</strong><small>Manual verification queue</small></div>
    <div className="wallet-summary-cell"><span>Wallet credits</span><strong>{q.data?.summary?.creditCount??ledger.filter(x=>x.type==='credit').length}</strong><small>Posted credit entries</small></div>
    <div className="wallet-summary-cell"><span>Wallet debits</span><strong>{q.data?.summary?.debitCount??ledger.filter(x=>x.type==='debit').length}</strong><small>Service and account movements</small></div>
   </div>
  </div>
  {q.isError?<div className="error-card">Could not load wallet. Reconnect and try again.</div>:null}
  <div className="wallet-recharge-shell">
   <div className="recharge-card wallet-recharge-card">
    <div className="section-heading"><div><span className="catalog-eyebrow">MANUAL UPI</span><h2>Add funds</h2><span className="section-subtle">Pay the exact amount, then submit the UTR for verification.</span></div>{q.data?.rechargeEnabled?<span className="payment-live-pill"><span/>Enabled</span>:null}</div>
    {pendingRecharges?<div className="info-card"><Icon name="clock" size={19}/><div><strong>{pendingRecharges} recharge request{pendingRecharges===1?' is':'s are'} already awaiting verification.</strong><p>You can submit another payment with a different UTR, but each request is credited only after manual verification.</p></div></div>:null}
    {q.data?.rechargeEnabled?<><div className="wallet-payment-destination"><div className="wallet-payment-destination-main"><span>Pay to {settings?.merchantName||'INBOX9'}</span><strong>{q.data.upiId}</strong><small>{settings?.instructions||'Pay the exact amount and keep your UTR / transaction reference.'}</small></div><button className="copy-button" type="button" onClick={()=>void copyUpi()}><Icon name="copy" size={16}/>{upiCopied?'Copied':'Copy UPI ID'}</button></div>
      <div className="wallet-payment-tools"><div className="wallet-amount-panel"><span className="card-label">1 · Choose amount</span><div className="quick-amounts">{[100,250,500,1000,2500,5000].map(v=><button key={v} type="button" className={amount===String(v)?'amount-chip is-selected':'amount-chip'} onClick={()=>{setAmount(String(v));setSent(false);setSubmittedRechargeId(null);setError(null)}}>₹{v}</button>)}</div><label className="field"><span>Custom amount</span><div className="money-input"><span>₹</span><input type="number" min="100" max="5000" step="1" value={amount} onChange={e=>{setAmount(e.target.value);setSent(false);setSubmittedRechargeId(null);setError(null)}} required/></div></label></div><div className="wallet-qr-panel"><span className="card-label">2 · Pay by UPI</span>{settings?.qrImage?<img className="wallet-payment-qr" src={settings.qrImage} alt="INBOX9 UPI payment QR code"/>:<div className="wallet-payment-qr-placeholder"><Icon name="wallet" size={24}/><span>Use the UPI ID shown above.</span></div>}{upiIntent?<button type="button" className="outline-button compact-button wallet-upi-open-button" onClick={openUpi}>Open UPI app <Icon name="arrow" size={15}/></button>:null}</div></div>
      {!paymentStarted?<button type="button" className="payment-paid-button" onClick={startPayment}><span className="payment-step-number">3</span><span><strong>I’ve completed the payment</strong><small>Continue to enter the UTR and, optionally, the payment time.</small></span><Icon name="arrow" size={17}/></button>:null}
      {paymentStarted?<form className="recharge-form wallet-recharge-form" onSubmit={e=>{e.preventDefault();setSent(false);setError(null);void recharge.mutate()}}><div className="payment-utr-head"><div><span className="card-label">3 · Confirm payment</span><strong>₹{(Number(amount||0)||0).toFixed(2)} payment</strong></div><button type="button" className="text-button compact-button" onClick={()=>setPaymentStarted(false)} disabled={recharge.isPending}>Back</button></div><label className="field"><span>UTR / transaction reference</span><input value={utr} onChange={e=>{setUtr(e.target.value);setSent(false)}} placeholder="Enter the UTR from your UPI payment" minLength={4} maxLength={64} autoComplete="off" required/></label><label className="field"><span>Payment completed at <small>(optional)</small></span><input type="datetime-local" value={customerPaidAt} onChange={e=>setCustomerPaidAt(e.target.value)} max={localDateTimeNow()}/><small>Helps the admin match the transaction in the payment record. Your wallet is not credited from this field.</small></label>{error?<div className="form-error" role="alert">{error}</div>:null}{sent&&!error?<div className="success-card"><Icon name="check" size={18}/><div><strong>Recharge submitted</strong><span>Reference: {submittedRechargeId||'recorded'} · Wallet credit is applied only after verification.</span><Link className="wallet-support-link" to={submittedRechargeId?'/support?category=recharge&rechargeId='+encodeURIComponent(submittedRechargeId):'/support'}>Need help with this recharge <Icon name="arrow" size={14}/></Link></div></div>:null}<div className="recharge-form-actions"><button type="submit" className="primary-button primary-button-large" disabled={recharge.isPending}>{recharge.isPending?'Submitting…':'Submit for verification'}<Icon name="arrow" size={18}/></button><button type="button" className="text-button" onClick={resetRechargeForm} disabled={recharge.isPending}>Reset</button></div></form>:null}
      <div className="wallet-payment-note"><Icon name="check" size={15}/><span>Manual verification protects the wallet from false client-side payment confirmations. Submitting a UTR does not itself add money.</span></div></>:<div className="info-card"><Icon name="clock" size={20}/><div><strong>Manual recharge is not enabled.</strong><p>No payment destination is shown until UPI recharge is configured for this deployment.</p></div></div>}
   </div><aside className="wallet-help-card"><span className="catalog-eyebrow">HOW IT WORKS</span><h3>Pay → verify → credit</h3><div className="wallet-help-step"><b>01</b><span>Choose an amount between ₹100 and ₹5,000.</span></div><div className="wallet-help-step"><b>02</b><span>Pay the exact amount to the INBOX9 UPI destination.</span></div><div className="wallet-help-step"><b>03</b><span>Submit the UTR and optional payment time. Keep the recharge reference.</span></div><div className="wallet-help-step"><b>04</b><span>Wallet balance changes only after server-side/admin verification.</span></div></aside>
  </div>
  <div className="wallet-section-heading"><div><span className="catalog-eyebrow">RECHARGES</span><h2>Recharge history</h2><span>{recharges.length?recharges.length+' request'+(recharges.length===1?'':'s'):'No recharge requests yet'}</span></div>{pendingRecharges?<span className="wallet-pending-pill">{pendingRecharges} pending</span>:<button type="button" className="text-button compact-button" onClick={()=>void q.refetch()} disabled={q.isFetching}>Refresh</button>}</div>
  <div className="wallet-filter-tabs" role="tablist" aria-label="Recharge history filter">{([['all','All'],['pending','Pending'],['review','Review'],['approved','Approved'],['rejected','Rejected']] as const).map(([value,label])=><button type="button" role="tab" aria-selected={rechargeFilter===value} className={rechargeFilter===value?'wallet-filter-tab is-selected':'wallet-filter-tab'} onClick={()=>setRechargeFilter(value)} key={value}>{label}</button>)}</div>
  {selectedRecharge?<div className="wallet-detail-card"><div className="wallet-detail-head"><div><span className="card-label">Recharge detail</span><h3>₹{(selectedRecharge.amountPaise/100).toFixed(2)}</h3></div><button className="sheet-close wallet-detail-close" type="button" aria-label="Close recharge details" onClick={()=>setDetail(null)}><Icon name="close" size={18}/></button></div><div className="wallet-detail-grid"><div><span>Status</span><strong className={'wallet-status-text wallet-status-'+statusMeta(selectedRecharge.status).tone}>{selectedRecharge.flaggedAt?'Review':statusMeta(selectedRecharge.status).label}</strong></div><div><span>Submitted</span><strong>{new Date(selectedRecharge.submittedAt).toLocaleString()}</strong></div>{selectedRecharge.customerPaidAt?<div><span>Paid at</span><strong>{new Date(selectedRecharge.customerPaidAt).toLocaleString()}</strong></div>:null}<div><span>UTR</span><strong>{selectedRecharge.utr}</strong></div>{selectedRecharge.reviewedAt?<div><span>Reviewed</span><strong>{new Date(selectedRecharge.reviewedAt).toLocaleString()}</strong></div>:null}{selectedRecharge.verifiedAmountPaise!=null?<div><span>Verified amount</span><strong>₹{(selectedRecharge.verifiedAmountPaise/100).toFixed(2)}</strong></div>:null}{selectedRecharge.verifiedUtr?<div><span>Verified UTR</span><strong>{selectedRecharge.verifiedUtr}</strong></div>:null}{selectedRecharge.externalReference?<div><span>External reference</span><strong>{selectedRecharge.externalReference}</strong></div>:null}{selectedRecharge.flagReason?<div className="wallet-detail-wide"><span>Review note</span><strong>{selectedRecharge.flagReason}</strong></div>:null}{selectedRecharge.rejectionReason?<div className="wallet-detail-wide"><span>Reason</span><strong>{selectedRecharge.rejectionReason}</strong></div>:null}</div><div className="wallet-payment-note"><Icon name={selectedRecharge.status.toLowerCase()==='approved'?'check':'clock'} size={15}/><span>{selectedRecharge.flaggedAt?'This request is under additional payment review.':String(selectedRecharge.status).toLowerCase().includes('pending')?'Waiting for admin verification.':selectedRecharge.rejectionReason?'The payment was not credited.':'This request has a recorded outcome.'}</span></div><Link className="wallet-support-link" to={'/support?category=recharge&rechargeId='+encodeURIComponent(selectedRecharge.id)}>Need help with this recharge <Icon name="arrow" size={15}/></Link></div>:null}
  {visibleRecharges.length?<div className="ledger-list wallet-recharge-list">{visibleRecharges.map(r=>{const meta=statusMeta(r.status);return <button className={'ledger-row ledger-row-button wallet-recharge-row'+(detail===r.id?' is-open':'')} type="button" key={r.id} onClick={()=>setDetail(previous=>previous===r.id?null:r.id)}><div><strong>₹{(r.amountPaise/100).toFixed(2)} recharge</strong><span>{new Date(r.submittedAt).toLocaleString()} · {r.utr}{r.customerPaidAt?' · paid '+new Date(r.customerPaidAt).toLocaleString():''}</span></div><b className={'wallet-status-pill wallet-status-'+(r.flaggedAt?'review':meta.tone)}>{r.flaggedAt?'Review':meta.label}</b></button>})}</div>:<div className="empty-state compact-empty"><h3>No matching recharge requests</h3><p>Use the filters above to switch between pending, review, approved, and rejected requests.</p></div>}
  <div className="wallet-section-heading"><div><span className="catalog-eyebrow">LEDGER</span><h2>Wallet activity</h2><span>Immutable credits and debits from your account</span></div><button type="button" className="text-button compact-button" onClick={()=>void q.refetch()} disabled={q.isFetching}>Refresh</button></div>
  <div className="wallet-filter-tabs" role="tablist" aria-label="Wallet activity filter">{([['all','All'],['credit','Credits'],['debit','Debits']] as const).map(([value,label])=><button type="button" role="tab" aria-selected={filter===value} className={filter===value?'wallet-filter-tab is-selected':'wallet-filter-tab'} onClick={()=>setFilter(value)} key={value}>{label}</button>)}</div>
  {filteredLedger.length?<div className="ledger-list">{filteredLedger.slice(0,50).map(i=><div className="ledger-row wallet-activity-row" key={i.id}><div><strong>{i.description||'Wallet transaction'}</strong><span>{new Date(i.createdAt ?? Date.now()).toLocaleString()} · {i.referenceType||'ledger'}</span></div><b className={i.type==='debit'?'ledger-debit':'ledger-credit'}>{i.type==='debit'?'−':'+'}₹{((i.amountPaise ?? 0)/100).toFixed(2)}</b></div>)}</div>:<div className="empty-state compact-empty"><h3>No {filter==='all'?'wallet activity':filter==='credit'?'credit':'debit'} transactions</h3><p>Transactions matching this filter will appear here.</p></div>}
 </section>
}

function NotificationsPage(){
 const client=useQueryClient();const q=useQuery({queryKey:['notifications'],queryFn:getNotifications,refetchInterval:15000});
 const markAll=useMutation({mutationFn:markAllNotificationsRead,onSuccess:async()=>{await client.invalidateQueries({queryKey:['notifications']})}});
 const markOne=useMutation({mutationFn:(id:string)=>markNotificationRead(id),onSuccess:async()=>{await client.invalidateQueries({queryKey:['notifications']})}});
 const [filter,setFilter]=useState<'all'|'unread'>('all');const items=q.data?.notifications??[];
 const unread=items.filter(n=>!n.read).length;const visible=filter==='unread'?items.filter(n=>!n.read):items;
 const target=(n:Notification)=>n.kind==='activation'&&n.sourceId?'/buy?activationId='+encodeURIComponent(n.sourceId):n.page==='wallet'?'/wallet':n.page==='support'?'/support':'/apps';
 function ago(t:number){const ms=Math.max(0,Date.now()-t);const m=Math.floor(ms/60000);if(m<1)return 'just now';if(m<60)return m+'m ago';const h=Math.floor(m/60);if(h<24)return h+'h ago';const d=Math.floor(h/24);return d<30?d+'d ago':new Date(t).toLocaleDateString()}
 function toneClass(n:Notification){return ['success','danger','warning','info'].includes(String(n.tone))?' notification-tone-'+n.tone:' notification-tone-info'}
 function iconFor(n:Notification):IconName{return n.kind==='activation'?'active':n.kind==='recharge'?'wallet':n.kind==='support'?'support':'bell'}
 return <section className="page-section notifications-page">
  <div className="catalog-heading notifications-heading"><div><h1>Notifications</h1><p>Account, wallet, activation and support updates in one place.</p></div>{unread?<span className="catalog-chip">{unread} unread</span>:<span className="catalog-chip">All caught up</span>}</div>
  <div className="notification-summary">
   <div><span>Inbox</span><strong>{items.length}</strong><small>{items.length===1?'update':'updates'}</small></div>
   <div><span>Unread</span><strong>{unread}</strong><small>{unread?'needs attention':'nothing pending'}</small></div>
   {unread?<button type="button" className="notification-mark-all" disabled={markAll.isPending} onClick={()=>void markAll.mutate()}>{markAll.isPending?'Marking...':'Mark all read'}</button>:null}
  </div>
  <div className="notification-filter-tabs" role="tablist" aria-label="Notification filter">
   <button type="button" role="tab" aria-selected={filter==='all'} className={filter==='all'?'notification-filter-tab is-selected':'notification-filter-tab'} onClick={()=>setFilter('all')}>All<span>{items.length}</span></button>
   <button type="button" role="tab" aria-selected={filter==='unread'} className={filter==='unread'?'notification-filter-tab is-selected':'notification-filter-tab'} onClick={()=>setFilter('unread')}>Unread<span>{unread}</span></button>
  </div>
  {q.isError?<div className="error-card">Notifications could not be loaded. Reconnect and retry.</div>:null}
  {visible.length?<div className="notification-list">{visible.map(n=><Link key={n.id} className={'notification-row'+(n.read?'':' unread')+toneClass(n)} to={target(n)} onClick={()=>{if(!n.read)void markOne.mutate(n.id)}}>
    <span className="notification-icon"><Icon name={iconFor(n)} size={19}/></span>
    <div className="notification-main"><div className="notification-title"><strong>{n.title}</strong><time dateTime={new Date(n.createdAt).toISOString()}>{ago(n.createdAt)}</time></div><p>{n.body}</p><span className="notification-link-label">Open {n.page==='active'?'activation':n.page==='wallet'?'wallet':n.page==='support'?'support':'app'} <Icon name="arrow" size={12}/></span></div>
    {!n.read?<span className="unread-dot" aria-label="Unread"/>:null}
  </Link>)}</div>:<div className="empty-state notification-empty"><div className="empty-icon"><Icon name="bell" size={28}/></div><h3>{filter==='unread'?'No unread notifications':'You’re all caught up'}</h3><p>{filter==='unread'?'Read updates stay in your notification history.':'New account, recharge, activation and support updates will appear here.'}</p>{filter==='unread'?<button type="button" className="outline-button compact-button" onClick={()=>setFilter('all')}>View all notifications</button>:null}</div>}
 </section>
}


function AccountPage(){
 const user=useSessionStore(s=>s.user);const setUser=useSessionStore(s=>s.setUser);const setBootstrap=useSessionStore(s=>s.setBootstrap);const navigate=useNavigate();const queryClient=useQueryClient();
 const [name,setName]=useState(user?.displayName||'');const [profileMsg,setProfileMsg]=useState<string|null>(null);const [profileError,setProfileError]=useState<string|null>(null);
 const [currentPassword,setCurrentPassword]=useState('');const [newPassword,setNewPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [securityError,setSecurityError]=useState<string|null>(null);const [securityMsg,setSecurityMsg]=useState<string|null>(null);
 const [recoveryCode,setRecoveryCode]=useState<string|null>(null);const [recoveryMsg,setRecoveryMsg]=useState<string|null>(null);const [copyMsg,setCopyMsg]=useState(false);const [accountRefresh,setAccountRefresh]=useState(false);
 const profile=useMutation({mutationFn:()=>updateProfile(name),onSuccess:r=>{setUser(r.user);setProfileMsg('Profile saved.');setProfileError(null)},onError:e=>setProfileError(e instanceof Error?e.message:'Profile update failed')});
 const password=useMutation({mutationFn:()=>changePassword(currentPassword,newPassword),onSuccess:r=>{setUser(r.user);setBootstrap('ready');setCurrentPassword('');setNewPassword('');setConfirmPassword('');setSecurityMsg('Password changed; previous sessions were invalidated.');setSecurityError(null)},onError:e=>setSecurityError(e instanceof Error?e.message:'Password change failed')});
 const recovery=useMutation({mutationFn:issueRecoveryCode,onSuccess:r=>{setRecoveryCode(r.code);setRecoveryMsg('One-time code generated. Store it somewhere safe before leaving this page.')},onError:e=>setRecoveryMsg(e instanceof Error?e.message:'Could not generate recovery code')});
 const sessions=useQuery({queryKey:['sessions'],queryFn:getSessions,staleTime:15000});
 const revoke=useMutation({mutationFn:(id:string)=>revokeSession(id),onSuccess:async()=>{await sessions.refetch()}});
 const all=useMutation({mutationFn:logoutAll,onSuccess:()=>{setUser(null);setBootstrap('signed-out');navigate('/login',{replace:true})}});
 async function refreshAccount(){setAccountRefresh(true);try{await Promise.all([sessions.refetch(),queryClient.invalidateQueries({queryKey:['wallet']}),queryClient.invalidateQueries({queryKey:['notifications']})])}finally{setAccountRefresh(false)}}
 async function copyRecovery(){if(!recoveryCode)return;try{await navigator.clipboard.writeText(recoveryCode);setCopyMsg(true);window.setTimeout(()=>setCopyMsg(false),1400)}catch{setRecoveryMsg('Copy is not available in this browser.')}}
 const sessionCount=sessions.data?.sessions.length??0;const policy=sessions.data?.policy;const currentSession=sessions.data?.sessions.find(s=>s.current);
 return <section className="page-section account-page">
  <div className="account-hero account-hero-rich"><div className="account-avatar">{(user?.displayName||user?.email||'I').slice(0,1).toUpperCase()}</div><div className="account-hero-copy"><h1>Account</h1><p>{user?.email}</p><span><span className="account-online-dot"/> Signed-in account</span></div><button className="account-refresh" type="button" onClick={()=>void refreshAccount()} disabled={accountRefresh} aria-label="Refresh account data"><Icon name="clock" size={17}/>{accountRefresh?'Refreshing…':'Refresh'}</button></div>
  <div className="account-security-banner"><div><span>Account security</span><strong>{sessionCount>1?'Multiple active sessions':'One active session'}</strong><small>{currentSession?'This device is signed in.':'Session status is currently unavailable.'}</small></div><span className="security-state"><Icon name="check" size={15}/> Protected</span></div>
  <div className="account-panels">
   <div className="account-panel account-panel-profile"><div className="section-heading"><div><h2>Profile</h2><span className="section-subtle">How your account is shown</span></div></div><form className="form-stack" onSubmit={e=>{e.preventDefault();void profile.mutate()}}><label className="field"><span>Display name</span><input value={name} onChange={e=>setName(e.target.value)} maxLength={64} placeholder="Add a display name"/></label>{profileError?<div className="form-error" role="alert">{profileError}</div>:null}{profileMsg?<div className="success-card" role="status"><Icon name="check" size={17}/><span>{profileMsg}</span></div>:null}<button className="primary-button" disabled={profile.isPending}>{profile.isPending?'Saving…':'Save profile'}</button></form></div>
   <div className="account-panel"><div className="section-heading"><div><h2>Password</h2><span className="section-subtle">Change your sign-in password</span></div></div><form className="form-stack" onSubmit={e=>{e.preventDefault();setSecurityError(null);if(newPassword!==confirmPassword){setSecurityError('New passwords do not match.');return}void password.mutate()}}><label className="field"><span>Current password</span><input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} autoComplete="current-password" required/></label><label className="field"><span>New password</span><input type="password" minLength={8} maxLength={128} value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoComplete="new-password" required/></label><label className="field"><span>Confirm new password</span><input type="password" minLength={8} maxLength={128} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} autoComplete="new-password" required/></label>{securityError?<div className="form-error" role="alert">{securityError}</div>:null}{securityMsg?<div className="success-card" role="status"><Icon name="check" size={17}/><span>{securityMsg}</span></div>:null}<button className="primary-button" disabled={password.isPending}>{password.isPending?'Updating…':'Change password'}</button></form></div>
   <div className="account-panel"><div className="section-heading"><div><h2>Recovery</h2><span className="section-subtle">Emergency password reset</span></div></div><p className="panel-copy">Generate a one-time recovery code while signed in. Use it from the recovery screen if you lose access to your password.</p>{recoveryCode?<div className="recovery-code"><code>{recoveryCode}</code><button className="copy-button" type="button" onClick={()=>void copyRecovery()}>{copyMsg?'Copied':'Copy'}</button></div>:null}{recoveryMsg?<div className="info-card" role="status">{recoveryMsg}</div>:null}<button className="outline-button" type="button" disabled={recovery.isPending} onClick={()=>void recovery.mutate()}>{recovery.isPending?'Generating…':'Generate recovery code'}</button><Link className="text-button compact-button" to="/recover">Open recovery screen <Icon name="arrow" size={14}/></Link></div>
   <div className="account-panel account-session-panel"><div className="section-heading"><div><h2>Sessions</h2><span className="section-subtle">Devices with access to your account</span></div><span className="catalog-chip">{sessionCount}</span></div>{sessions.isPending?<div className="session-list"><div className="session-skeleton"/><div className="session-skeleton"/></div>:null}{sessions.isError?<div className="error-card" role="alert">Could not load sessions. <button type="button" className="inline-retry" onClick={()=>void sessions.refetch()}>Retry</button></div>:null}{sessions.data?.sessions.length?<div className="session-list">{sessions.data.sessions.map(s=><div className={'session-row'+(s.current?' session-row-current':'')} key={s.id}><div><strong>{s.current?'This device':'Other session'}</strong><span>Created {new Date(s.createdAt).toLocaleString()}</span><span>Last used {s.lastUsedAt?new Date(s.lastUsedAt).toLocaleString():'—'}</span>{s.expiresAt?<span>Expires {new Date(s.expiresAt).toLocaleString()}</span>:null}</div>{!s.current?<button className="text-button" type="button" disabled={revoke.isPending} onClick={()=>void revoke.mutate(s.id)}>Revoke</button>:<span className="current-session">Current</span>}</div>)}</div>:sessions.isSuccess?<div className="empty-state compact-empty"><h3>No additional sessions</h3><p>Only this device currently has access.</p></div>:null}<div className="session-policy">{policy?<span>Session limit {policy.maxSessionsPerUser} · Absolute lifetime {policy.absoluteDays} days</span>:<span>Session policy is managed securely by INBOX9.</span>}<button type="button" className="inline-retry" onClick={()=>void sessions.refetch()} disabled={sessions.isFetching}>Refresh</button></div><button className="secondary-danger" type="button" disabled={all.isPending} onClick={()=>void all.mutate()}>{all.isPending?'Signing out…':'Sign out everywhere'}</button></div>
   <div className="account-panel"><div className="section-heading"><div><h2>Account tools</h2><span className="section-subtle">Keep the important actions close</span></div></div><div className="menu-card"><Link to="/wallet" className="menu-row"><span><Icon name="wallet" size={20}/><b>Wallet & recharge</b></span><Icon name="arrow" size={18}/></Link><Link to="/notifications" className="menu-row"><span><Icon name="bell" size={20}/><b>Notifications</b></span><Icon name="arrow" size={18}/></Link><Link to="/support" className="menu-row"><span><Icon name="support" size={20}/><b>Support</b></span><Icon name="arrow" size={18}/></Link></div></div>
   <div className="account-panel account-resilience-panel"><div className="section-heading"><div><h2>Resilience</h2><span className="section-subtle">Connection and account-data recovery</span></div></div><div className="resilience-row"><span className="resilience-indicator is-online"/><div><strong>Connection available</strong><small>INBOX9 refreshes account data when connectivity returns.</small></div></div><button className="outline-button" type="button" onClick={()=>void refreshAccount()} disabled={accountRefresh}>{accountRefresh?'Refreshing account data…':'Refresh account data'}<Icon name="clock" size={16}/></button></div>
   <div className="account-panel"><button className="secondary-danger" type="button" disabled={all.isPending} onClick={()=>void all.mutate()}>{all.isPending?'Signing out…':'Sign out'}</button><p className="panel-copy">Your profile, sessions, password and recovery controls are handled server-side.</p></div>
  </div>
 </section>
}

function SupportPage(){
 const [params]=useSearchParams();const q=useQuery({queryKey:['support'],queryFn:getSupportTickets,refetchInterval:30000});
 const [view,setView]=useState<'open'|'history'>('open');const [category,setCategory]=useState(params.get('category')||'activation');
 const [subject,setSubject]=useState('');const [message,setMessage]=useState('');const [activationId,setActivationId]=useState(params.get('activationId')||'');const [rechargeId,setRechargeId]=useState(params.get('rechargeId')||'');const [error,setError]=useState<string|null>(null);const [sent,setSent]=useState(false);
 const create=useMutation({mutationFn:()=>createSupportTicket({category,subject,message,activationId:activationId||undefined,rechargeId:rechargeId||undefined}),onSuccess:async()=>{setSent(true);setError(null);setSubject('');setMessage('');await q.refetch()},onError:e=>setError(e instanceof Error?e.message:'Could not submit support request')});
 const tickets=q.data?.tickets??[];const openTickets=tickets.filter(t=>t.status==='Open'||t.status==='In Progress');const historyTickets=tickets.filter(t=>!openTickets.includes(t));const visible=view==='open'?openTickets:historyTickets;
 const categories=[['activation','Activation'],['recharge','Recharge'],['wallet','Wallet'],['account','Account'],['other','Other']] as const;
 const linked=activationId||rechargeId;
 return <section className="page-section support-page">
  <div className="catalog-heading"><div><h1>Support</h1><p>Get help, keep references attached, and continue every conversation in one thread.</p></div><span className="catalog-chip">{tickets.length} {tickets.length===1?'ticket':'tickets'}</span></div>
  <div className="support-quick-grid">
   <Link to="/support?category=activation" className="support-quick-card"><span className="support-quick-icon"><Icon name="active" size={18}/></span><div><strong>Activation help</strong><small>Number, OTP or cancellation</small></div><Icon name="arrow" size={15}/></Link>
   <Link to="/support?category=recharge" className="support-quick-card"><span className="support-quick-icon"><Icon name="wallet" size={18}/></span><div><strong>Recharge help</strong><small>UTR, verification or wallet credit</small></div><Icon name="arrow" size={15}/></Link>
  </div>
  <div className="support-view-tabs" role="tablist" aria-label="Support ticket views"><button type="button" role="tab" aria-selected={view==='open'} className={view==='open'?'support-view-tab is-selected':'support-view-tab'} onClick={()=>setView('open')}>Open<span>{openTickets.length}</span></button><button type="button" role="tab" aria-selected={view==='history'} className={view==='history'?'support-view-tab is-selected':'support-view-tab'} onClick={()=>setView('history')}>History<span>{historyTickets.length}</span></button></div>
  <div className="support-layout">
   <div className="support-panel support-compose">
    <div className="section-heading"><div><h2>New request</h2><span className="section-subtle">Start with the issue type</span></div></div>
    <div className="support-category-grid" aria-label="Support category">{categories.map(([value,label])=><button key={value} type="button" className={category===value?'support-category-chip is-selected':'support-category-chip'} onClick={()=>setCategory(value)}>{label}</button>)}</div>
    {linked?<div className="support-linked-context">{activationId?<Link to={'/active/'+encodeURIComponent(activationId)}><Icon name="active" size={14}/> Linked activation <span>{activationId}</span></Link>:null}{rechargeId?<Link to="/wallet"><Icon name="wallet" size={14}/> Linked recharge <span>{rechargeId}</span></Link>:null}</div>:null}
    <form className="support-form" onSubmit={e=>{e.preventDefault();setSent(false);setError(null);void create.mutate()}}>
     <label className="field"><span>Subject</span><input value={subject} onChange={e=>setSubject(e.target.value)} minLength={4} maxLength={120} placeholder="What do you need help with?" required/></label>
     <label className="field"><span>Message</span><textarea value={message} onChange={e=>setMessage(e.target.value)} minLength={10} maxLength={2000} placeholder="Give us the details and we’ll keep the conversation here." required/></label>
     <details className="support-reference-details"><summary>Add reference</summary><div className="support-reference-fields"><label className="field"><span>Activation reference</span><input value={activationId} onChange={e=>setActivationId(e.target.value)} placeholder="Activation ID"/></label><label className="field"><span>Recharge reference</span><input value={rechargeId} onChange={e=>setRechargeId(e.target.value)} placeholder="Recharge ID"/></label></div></details>
     {error?<div className="form-error" role="alert">{error}</div>:null}{sent?<div className="success-card"><Icon name="check" size={18}/><span>Ticket created. Open it below to continue the thread.</span></div>:null}
     <button className="primary-button" disabled={create.isPending}>{create.isPending?'Sending...':'Open support ticket'}<Icon name="arrow" size={17}/></button>
    </form>
   </div>
   <div className="support-panel support-ticket-panel"><div className="section-heading"><div><h2>{view==='open'?'Open tickets':'Ticket history'}</h2><span className="section-subtle">{view==='open'?'Replies and active conversations first.':'Resolved and closed conversations.'}</span></div></div>
    {q.isError?<div className="error-card">Support could not be loaded. Reconnect and retry.</div>:null}
    {visible.length?<div className="ticket-list">{visible.map(t=>{const last=t.messages?.[t.messages.length-1];const hasAdminReply=last?.authorRole==='admin';return <Link key={t.id} to={'/support/'+encodeURIComponent(t.id)} className="ticket-row ticket-row-rich"><span className="ticket-status-icon"><Icon name={t.category==='activation'?'active':t.category==='recharge'||t.category==='wallet'?'wallet':'support'} size={17}/></span><div className="ticket-row-copy"><div className="ticket-row-title"><strong>{t.subject}</strong><span className={'support-status support-status-'+t.status.toLowerCase().replace(/\s+/g,'-')}>{t.status}</span></div><span>{hasAdminReply?'Support replied · ':''}{new Date(t.updatedAt).toLocaleString()}</span>{t.activation?<span>Activation · {t.activation.service||t.activation.id}</span>:null}{t.recharge?<span>Recharge · ₹{((t.recharge.amountPaise ?? 0)/100).toFixed(2)} · {t.recharge.status}</span>:null}</div><Icon name="arrow" size={17}/></Link>})}</div>:<div className="empty-state compact-empty"><div className="empty-icon"><Icon name="support" size={24}/></div><h3>{view==='open'?'No open tickets':'No ticket history'}</h3><p>{view==='open'?'Start a request and your conversation will appear here.':'Resolved and closed requests will remain available here.'}</p></div>}
   </div>
  </div>
 </section>
}

function SupportThreadPage(){
 const {ticketId}=useParams();const q=useQuery({queryKey:['support'],queryFn:getSupportTickets,refetchInterval:15000});const [message,setMessage]=useState('');const [error,setError]=useState<string|null>(null);const client=useQueryClient();
 const ticket=q.data?.tickets.find(t=>t.id===ticketId);
 const reply=useMutation({mutationFn:()=>replySupportTicket(ticketId ?? '',message),onSuccess:async()=>{setMessage('');setError(null);await client.invalidateQueries({queryKey:['support']})},onError:e=>setError(e instanceof Error?e.message:'Reply failed')});
 if(q.isPending)return <section className="page-section"><div className="page-loading">Loading ticket...</div></section>;
 if(!ticket)return <section className="page-section"><Link className="back-link" to="/support"><Icon name="back" size={18}/> Support</Link><div className="error-card">Ticket not found.</div></section>;
 const messages=ticket.messages?.length?ticket.messages:[{id:'initial',authorRole:'customer',body:ticket.message,createdAt:ticket.createdAt}];
 const canReply=ticket.status!=='Closed';
 return <section className="page-section support-thread-page"><Link className="back-link" to="/support"><Icon name="back" size={18}/> Support</Link>
  <div className="ticket-thread-hero"><div><span className="card-label">Support ticket</span><h1>{ticket.subject}</h1><div className="ticket-thread-meta"><span className={'support-status support-status-'+ticket.status.toLowerCase().replace(/\s+/g,'-')}>{ticket.status}</span><span>{ticket.category}</span><span>{messages.length} {messages.length===1?'message':'messages'}</span><span>Updated {new Date(ticket.updatedAt).toLocaleString()}</span></div></div></div>
  {ticket.activation||ticket.recharge?<div className="reference-strip">{ticket.activation?<Link to={'/active/'+encodeURIComponent(ticket.activation.id)}><Icon name="active" size={14}/> Activation · {ticket.activation.service||ticket.activation.id}</Link>:null}{ticket.recharge?<Link to="/wallet"><Icon name="wallet" size={14}/> Recharge · ₹{((ticket.recharge.amountPaise ?? 0)/100).toFixed(2)} · {ticket.recharge.status}</Link>:null}</div>:null}
  <div className="message-thread support-message-thread">{messages.map(m=><div className={'thread-message '+(m.authorRole==='admin'?'from-admin':'from-customer')} key={m.id}><div className="thread-message-head"><span>{m.authorRole==='admin'?'INBOX9 Support':'You'}</span><time>{new Date(m.createdAt).toLocaleString()}</time></div><p>{m.body}</p></div>)}</div>
  {canReply?<form className="reply-form support-reply-form" onSubmit={e=>{e.preventDefault();setError(null);if(message.trim().length<2){setError('Reply must be at least 2 characters.');return}void reply.mutate()}}><div className="reply-form-heading"><div><strong>Continue the conversation</strong><span>Keep the original ticket reference attached.</span></div></div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a reply..." maxLength={4000} required/>{error?<div className="form-error" role="alert">{error}</div>:null}<button className="primary-button" disabled={reply.isPending}>{reply.isPending?'Sending...':'Send reply'}<Icon name="arrow" size={18}/></button></form>:<div className="info-card"><Icon name="check" size={19}/><div><strong>This ticket is closed.</strong><p>Create a new ticket for further help.</p></div></div>}
 </section>
}



export { WalletPage, NotificationsPage, SupportPage, SupportThreadPage, AccountPage };
