import { SERVICE_LOGO_SPRITE_PATH } from './serviceLogoSprite';

// Generated from the preprocessed 2026-09-25 HD logo packages.
// The customer catalog is fixed at 90 services; the browser receives finished tiles only.
export const SERVICE_LOGO_SPRITE = {
  path: SERVICE_LOGO_SPRITE_PATH,
  tileSize: 48,
  columns: 10,
  rows: 9
} as const;

export const SERVICE_LOGO_MANIFEST: Record<string, { spriteIndex: number }> = {
  "svc-joy-rummy": { "spriteIndex": 0 },
  "svc-ind-rummy": { "spriteIndex": 1 },
  "svc-inr-rummy": { "spriteIndex": 2 },
  "svc-rumble-rummy": { "spriteIndex": 3 },
  "svc-bingo-101": { "spriteIndex": 4 },
  "svc-spin-101": { "spriteIndex": 5 },
  "svc-diwa-top": { "spriteIndex": 6 },
  "svc-jaiho-slots": { "spriteIndex": 7 },
  "svc-rummy-91": { "spriteIndex": 8 },
  "svc-max-rummy": { "spriteIndex": 9 },
  "svc-gold-rummy": { "spriteIndex": 10 },
  "svc-win-rummy": { "spriteIndex": 11 },
  "svc-diwa-x": { "spriteIndex": 12 },
  "svc-jaiho-rummy": { "spriteIndex": 13 },
  "svc-jaiho-91": { "spriteIndex": 14 },
  "svc-diwa-win": { "spriteIndex": 15 },
  "svc-maha-games": { "spriteIndex": 16 },
  "svc-jaiho-777-vip": { "spriteIndex": 17 },
  "svc-rummy-888": { "spriteIndex": 18 },
  "svc-dhan-game": { "spriteIndex": 19 },
  "svc-diwa-game": { "spriteIndex": 20 },
  "svc-diwa-vip": { "spriteIndex": 21 },
  "svc-ind-club": { "spriteIndex": 22 },
  "svc-diwa-slots": { "spriteIndex": 23 },
  "svc-diwa-777": { "spriteIndex": 24 },
  "svc-spin-crush": { "spriteIndex": 25 },
  "svc-spin-winner": { "spriteIndex": 26 },
  "svc-spin-gold": { "spriteIndex": 27 },
  "svc-slots-winner": { "spriteIndex": 28 },
  "svc-rummy-ludo": { "spriteIndex": 29 },
  "svc-jaiho-spin": { "spriteIndex": 30 },
  "svc-yono-777": { "spriteIndex": 31 },
  "svc-rummy-77": { "spriteIndex": 32 },
  "svc-777-game": { "spriteIndex": 33 },
  "svc-club-inr": { "spriteIndex": 34 },
  "svc-winzo-rummy": { "spriteIndex": 35 },
  "svc-rummy-app": { "spriteIndex": 36 },
  "svc-ever-777": { "spriteIndex": 37 },
  "svc-inr-slots": { "spriteIndex": 38 },
  "svc-good-slots": { "spriteIndex": 39 },
  "svc-boss-rummy": { "spriteIndex": 40 },
  "svc-hindi-777": { "spriteIndex": 41 },
  "svc-yn-777": { "spriteIndex": 42 },
  "svc-yes-spin": { "spriteIndex": 43 },
  "svc-ok-rummy": { "spriteIndex": 44 },
  "svc-love-rummy": { "spriteIndex": 45 },
  "svc-share-slots": { "spriteIndex": 46 },
  "svc-hi-rummy": { "spriteIndex": 47 },
  "svc-jaiho-win": { "spriteIndex": 48 },
  "svc-goa-spin": { "spriteIndex": 49 },
  "svc-slots-spin": { "spriteIndex": 50 },
  "svc-mqm-bet": { "spriteIndex": 51 },
  "svc-saga-slots": { "spriteIndex": 52 },
  "svc-rummy-yono": { "spriteIndex": 53 },
  "svc-abc-rummy": { "spriteIndex": 54 },
  "svc-jaiho-arcade": { "spriteIndex": 55 },
  "svc-neta-vip": { "spriteIndex": 56 },
  "svc-mwm-bet": { "spriteIndex": 57 },
  "svc-en-365": { "spriteIndex": 58 },
  "svc-101z-app": { "spriteIndex": 59 },
  "svc-rummy-365": { "spriteIndex": 60 },
  "svc-ind-bingo": { "spriteIndex": 61 },
  "svc-my-777": { "spriteIndex": 62 },
  "svc-bet-213-slots": { "spriteIndex": 63 },
  "svc-gogo-rummy": { "spriteIndex": 64 },
  "svc-789-jackpot": { "spriteIndex": 65 },
  "svc-mdm-bet": { "spriteIndex": 66 },
  "svc-spin-lucky": { "spriteIndex": 67 },
  "svc-ind-slots": { "spriteIndex": 68 },
  "svc-mkm-bet": { "spriteIndex": 69 },
  "svc-yono-maha-games": { "spriteIndex": 70 },
  "svc-game-rummy": { "spriteIndex": 71 },
  "svc-mbm-bet": { "spriteIndex": 72 },
  "svc-jaiho-777": { "spriteIndex": 73 },
  "svc-top-rummy": { "spriteIndex": 74 },
  "svc-spin-777": { "spriteIndex": 75 },
  "svc-567-slots": { "spriteIndex": 76 },
  "svc-yono-vip": { "spriteIndex": 77 },
  "svc-yono-slots": { "spriteIndex": 78 },
  "svc-yono-rummy": { "spriteIndex": 79 },
  "svc-yono-games": { "spriteIndex": 80 },
  "svc-money-rummy": { "spriteIndex": 81 },
  "svc-yn-rummy": { "spriteIndex": 82 },
  "svc-yoyo-slots": { "spriteIndex": 83 },
  "svc-svip-777": { "spriteIndex": 84 },
  "svc-rummy-zip": { "spriteIndex": 85 },
  "svc-diwa-lucky": { "spriteIndex": 86 },
  "svc-diwa-ace": { "spriteIndex": 87 },
  "svc-diwa-king": { "spriteIndex": 88 },
  "svc-diwa-play": { "spriteIndex": 89 },
};