import { SERVICE_LOGO_SPRITE_PATH } from './serviceLogoSprite';

export const SERVICE_LOGO_SPRITE = {
  path: SERVICE_LOGO_SPRITE_PATH,
  tileSize: 128,
  columns: 9,
  rows: 10,
} as const;

// Prepared from the user-supplied ZIP. Only services with a matching supplied icon are mapped.
// Missing catalog services intentionally render as black blank tiles.
export const SERVICE_LOGO_MANIFEST: Record<string, { spriteIndex: number }> = {
  'svc-101z-app': { spriteIndex: 0 },
  'svc-567-slots': { spriteIndex: 1 },
  'svc-777-game': { spriteIndex: 2 },
  'svc-789-jackpot': { spriteIndex: 3 },
  'svc-abc-rummy': { spriteIndex: 4 },
  'svc-bet-213-slots': { spriteIndex: 5 },
  'svc-bingo-101': { spriteIndex: 6 },
  'svc-boss-rummy': { spriteIndex: 7 },
  'svc-club-inr': { spriteIndex: 8 },
  'svc-dhan-game': { spriteIndex: 9 },
  'svc-diwa-777': { spriteIndex: 10 },
  'svc-diwa-game': { spriteIndex: 11 },
  'svc-diwa-king': { spriteIndex: 12 },
  'svc-diwa-lucky': { spriteIndex: 13 },
  'svc-diwa-play': { spriteIndex: 14 },
  'svc-diwa-slots': { spriteIndex: 15 },
  'svc-diwa-top': { spriteIndex: 16 },
  'svc-diwa-vip': { spriteIndex: 17 },
  'svc-diwa-win': { spriteIndex: 18 },
  'svc-diwa-x': { spriteIndex: 19 },
  'svc-ever-777': { spriteIndex: 20 },
  'svc-game-rummy': { spriteIndex: 21 },
  'svc-gogo-rummy': { spriteIndex: 22 },
  'svc-gold-rummy': { spriteIndex: 23 },
  'svc-good-slots': { spriteIndex: 24 },
  'svc-hi-rummy': { spriteIndex: 25 },
  'svc-hindi-777': { spriteIndex: 26 },
  'svc-ind-club': { spriteIndex: 27 },
  'svc-ind-rummy': { spriteIndex: 28 },
  'svc-ind-slots': { spriteIndex: 29 },
  'svc-inr-rummy': { spriteIndex: 30 },
  'svc-jaiho-777': { spriteIndex: 31 },
  'svc-jaiho-777-vip': { spriteIndex: 32 },
  'svc-jaiho-91': { spriteIndex: 33 },
  'svc-jaiho-arcade': { spriteIndex: 34 },
  'svc-jaiho-rummy': { spriteIndex: 35 },
  'svc-jaiho-slots': { spriteIndex: 36 },
  'svc-jaiho-spin': { spriteIndex: 37 },
  'svc-jaiho-win': { spriteIndex: 38 },
  'svc-joy-rummy': { spriteIndex: 39 },
  'svc-love-rummy': { spriteIndex: 40 },
  'svc-maha-games': { spriteIndex: 41 },
  'svc-max-rummy': { spriteIndex: 42 },
  'svc-mbm-bet': { spriteIndex: 43 },
  'svc-money-rummy': { spriteIndex: 44 },
  'svc-mqm-bet': { spriteIndex: 45 },
  'svc-neta-vip': { spriteIndex: 46 },
  'svc-ok-rummy': { spriteIndex: 47 },
  'svc-rumble-rummy': { spriteIndex: 48 },
  'svc-rummy-77': { spriteIndex: 49 },
  'svc-rummy-888': { spriteIndex: 50 },
  'svc-rummy-91': { spriteIndex: 51 },
  'svc-rummy-ludo': { spriteIndex: 52 },
  'svc-saga-slots': { spriteIndex: 53 },
  'svc-share-slots': { spriteIndex: 54 },
  'svc-slots-spin': { spriteIndex: 55 },
  'svc-slots-winner': { spriteIndex: 56 },
  'svc-spin-101': { spriteIndex: 57 },
  'svc-spin-777': { spriteIndex: 58 },
  'svc-spin-crush': { spriteIndex: 59 },
  'svc-spin-gold': { spriteIndex: 60 },
  'svc-spin-winner': { spriteIndex: 61 },
  'svc-top-rummy': { spriteIndex: 62 },
  'svc-win-rummy': { spriteIndex: 63 },
  'svc-yes-spin': { spriteIndex: 64 },
  'svc-yn-777': { spriteIndex: 65 },
  'svc-yono-777': { spriteIndex: 66 },
  'svc-yono-games': { spriteIndex: 67 },
  'svc-yono-rummy': { spriteIndex: 68 },
  'svc-yono-slots': { spriteIndex: 69 },
  'svc-yono-vip': { spriteIndex: 70 },
};
