import { apiRequest } from './client';

export type AdminOverview={users:number;activeActivations:number;rechargeRequests:number;pendingRechargePaise:number;walletBalancePaise:number;approvedRechargePaise:number;totalDebitsPaise:number;persistent:boolean};
export type AdminUser={id:string;email:string;role:string;active:boolean;displayName:string;createdAt:number;balancePaise:number;rechargeCount:number;activationCount:number};
export type AdminUsersResponse={users:AdminUser[];summary:{total:number;active:number;disabled:number;admins:number}};
export type AdminUserDetailResponse={user:AdminUser;summary:{supportCount:number;activeSessions:number};sessions:Array<{id:string;createdAt:number;lastUsedAt:number|null;expiresAt:number;revokedAt:number|null;active:boolean}>;recharges:Array<{id:string;amountPaise:number;utr:string;paymentMethod:string;status:string;submittedAt:number;reviewedAt:number|null;rejectionReason:string|null;externalReference:string|null}>;activations:Array<{id:string;serviceId:string;service:string|null;status:string;pricePaise:number;number:string|null;otp:string|null;createdAt:number;expiresAt:number;updatedAt:number}>;support:Array<{id:string;category:string;subject:string;status:string;createdAt:number;updatedAt:number}>};
export function getAdminOverview(){return apiRequest<AdminOverview>('/api/admin/overview');}
export function getAdminUsers(params:{q?:string;role?:string;status?:string;limit?:number}={}){const p=new URLSearchParams();if(params.q)p.set('q',params.q);if(params.role&&params.role!=='all')p.set('role',params.role);if(params.status&&params.status!=='all')p.set('status',params.status);if(params.limit)p.set('limit',String(params.limit));return apiRequest<AdminUsersResponse>('/api/admin/users'+(p.toString()?'?'+p.toString():''));}
export function getAdminUser(id:string){return apiRequest<AdminUserDetailResponse>('/api/admin/users/'+encodeURIComponent(id));}
export function updateAdminUser(id:string,action:'enable'|'disable'|'logout_all'){return apiRequest<{active?:boolean;changed?:boolean;revokedSessions?:number}>('/api/admin/users/'+encodeURIComponent(id),{method:'POST',body:JSON.stringify({action})});}
