export const NAV = [
  ['buy', 'Buy Number', '▣'],
  ['active', 'Active', '◌'],
  ['orders', 'Orders', '▤'],
  ['wallet', 'Wallet', '▱'],
  ['support', 'Help & Support', '?'],
  ['account', 'Account', '◉']
];

export const DEFAULT_CATEGORIES = ['Social', 'Productivity', 'Rummy', 'Games', 'Other'];
export const MARKET_PAGE_SIZE = 48;
export const MARKET_MAX_SEARCH_RESULTS = 96;

export function createCustomerState() {
  return {
    page: 'buy',
    search: '',
    category: 'All',
    balancePaise: 0,
    walletLedger: [],
    walletSummary: { creditPaise: 0, debitPaise: 0, pendingPaise: 0, creditCount: 0, debitCount: 0, pendingCount: 0 },
    recharges: [],
    rechargeAmount: 100,
    notifications: [],
    notificationsOpen: false,
    notificationsNextId: 1,
    notificationLoading: false,
    notificationError: '',
    online: typeof navigator === 'undefined' ? true : navigator.onLine,
    reconnecting: false,
    supportTickets: [],
    supportLoading: false,
    supportSubmitting: false,
    supportReplyBusyById: {},
    expandedSupportTicketId: null,
    supportError: '',
    supportForm: { category: 'activation', subject: '', message: '', activationId: '', rechargeId: '' },
    lastSupportSyncAt: 0,
    rechargeSubmitting: false,
    walletFilter: 'all',
    expandedWalletTransactionId: null,
    orderFilter: 'all',
    expandedOrderId: null,
    services: [],
    active: [],
    recentActivations: [],
    activeCancelId: null,
    activeCancelBusy: new Set(),
    activeActionErrorById: {},
    orders: [],
    loading: true,
    error: '',
    bootstrapError: '',
    persistentState: false,
    rechargeUpiId: null,
    mobileMenu: false,
    toastTimer: null,
    user: null,
    authMode: 'login',
    adminTab: 'overview',
    adminLoading: false,
    adminError: '',
    admin: { overview: null, recharges: [], users: [], services: [], activations: [], ledger: [], audit: [], providers: [], support: [] },
    adminSupportFilter: 'all',
    pendingPurchaseKeys: {},
    purchaseBusy: new Set(),
    securityOpen: false,
    dialogReturnFocus: null,
    accountLoading: false,
    accountError: '',
    accountSessions: [],
    accountRecoveryCode: '',
    accountRecoveryBusy: false,
    expandedServiceId: null,
    marketVisibleCount: MARKET_PAGE_SIZE,
    categoryCounts: {},
    catalogCategories: ['All'],
    serviceSearchIndex: [],
    marketSearchTimer: null,
    marketUrlSyncTimer: null,
    lastCatalogRefreshAt: 0,
    catalogLoading: false,
    catalogError: '',
    customerDataRefreshing: false,
    lastActivationSyncAt: 0,
    activeSyncError: '',
    tickTimer: null,
    purchaseFlow: {
      step: 'service',
      serviceId: null,
      serverId: null,
      submitting: false,
      error: '',
      errorCode: '',
      returnAfterWallet: false
    }
  };
}
