-- INBOX9 catalog cutover to the 2026-09-25 master service list.
-- The master list supplies canonical service names/order only; catalog metadata is initialized
-- with the existing provisional Other / INR 10 default until provider pricing metadata is configured.
-- Historical rows and activation references are preserved: old services are deactivated, not deleted.
-- New IDs are stable slugs and are independent of row position.
BEGIN;

UPDATE service_provider_routes SET active=FALSE WHERE active=TRUE;
UPDATE services SET active=FALSE WHERE active=TRUE;

WITH new_services(id,name,category,currency,price_paise,country,availability,stock,active) AS (
VALUES
  ('svc-yono-bonus-51','Yono Bonus 51','Other','INR',1000,'IN','medium',104,TRUE),
  ('svc-joy-rummy','Joy Rummy','Other','INR',1000,'IN','high',77,TRUE),
  ('svc-ind-rummy','IND Rummy','Other','INR',1000,'IN','high',100,TRUE),
  ('svc-inr-rummy','INR Rummy','Other','INR',1000,'IN','high',76,TRUE),
  ('svc-rumble-rummy','Rumble Rummy','Other','INR',1000,'IN','high',50,TRUE),
  ('svc-bingo-101','Bingo 101','Other','INR',1000,'IN','medium',44,TRUE),
  ('svc-spin-101','Spin 101','Other','INR',1000,'IN','high',77,TRUE),
  ('svc-diwa-top','Diwa Top','Other','INR',1000,'IN','high',71,TRUE),
  ('svc-jaiho-slots','Jaiho Slots','Other','INR',1000,'IN','high',77,TRUE),
  ('svc-rummy-91','Rummy 91','Other','INR',1000,'IN','high',113,TRUE),
  ('svc-max-rummy','Max Rummy','Other','INR',1000,'IN','high',105,TRUE),
  ('svc-gold-rummy','Gold Rummy','Other','INR',1000,'IN','high',27,TRUE),
  ('svc-win-rummy','Win Rummy','Other','INR',1000,'IN','high',55,TRUE),
  ('svc-diwa-x','Diwa X','Other','INR',1000,'IN','high',82,TRUE),
  ('svc-jaiho-rummy','Jaiho Rummy','Other','INR',1000,'IN','high',60,TRUE),
  ('svc-jaiho-91','Jaiho 91','Other','INR',1000,'IN','medium',104,TRUE),
  ('svc-diwa-win','Diwa Win','Other','INR',1000,'IN','high',62,TRUE),
  ('svc-maha-games','Maha Games','Other','INR',1000,'IN','high',43,TRUE),
  ('svc-jaiho-777-vip','Jaiho 777 VIP','Other','INR',1000,'IN','high',113,TRUE),
  ('svc-rummy-888','Rummy 888','Other','INR',1000,'IN','high',101,TRUE),
  ('svc-dhan-game','Dhan Game','Other','INR',1000,'IN','medium',44,TRUE),
  ('svc-diwa-game','Diwa Game','Other','INR',1000,'IN','high',96,TRUE),
  ('svc-diwa-vip','Diwa VIP','Other','INR',1000,'IN','high',37,TRUE),
  ('svc-ind-club','IND Club','Other','INR',1000,'IN','high',90,TRUE),
  ('svc-all-yono-games','All Yono Games','Other','INR',1000,'IN','high',93,TRUE),
  ('svc-diwa-slots','Diwa Slots','Other','INR',1000,'IN','high',83,TRUE),
  ('svc-diwa-777','DIWA 777','Other','INR',1000,'IN','high',35,TRUE),
  ('svc-spin-crush','Spin Crush','Other','INR',1000,'IN','high',32,TRUE),
  ('svc-spin-winner','Spin Winner','Other','INR',1000,'IN','high',66,TRUE),
  ('svc-spin-gold','Spin Gold','Other','INR',1000,'IN','medium',99,TRUE),
  ('svc-slots-winner','Slots Winner','Other','INR',1000,'IN','high',113,TRUE),
  ('svc-rummy-ludo','Rummy Ludo','Other','INR',1000,'IN','medium',89,TRUE),
  ('svc-jaiho-spin','Jaiho Spin','Other','INR',1000,'IN','high',76,TRUE),
  ('svc-yono-777','Yono 777','Other','INR',1000,'IN','high',81,TRUE),
  ('svc-rummy-77','Rummy 77','Other','INR',1000,'IN','high',97,TRUE),
  ('svc-777-game','777 Game','Other','INR',1000,'IN','high',56,TRUE),
  ('svc-club-inr','Club INR','Other','INR',1000,'IN','high',56,TRUE),
  ('svc-winzo-rummy','Winzo Rummy','Other','INR',1000,'IN','medium',84,TRUE),
  ('svc-rummy-app','Rummy App','Other','INR',1000,'IN','high',40,TRUE),
  ('svc-ever-777','Ever 777','Other','INR',1000,'IN','high',50,TRUE),
  ('svc-inr-slots','INR Slots','Other','INR',1000,'IN','high',97,TRUE),
  ('svc-good-slots','Good Slots','Other','INR',1000,'IN','high',67,TRUE),
  ('svc-boss-rummy','Boss Rummy','Other','INR',1000,'IN','medium',64,TRUE),
  ('svc-hindi-777','Hindi 777','Other','INR',1000,'IN','high',38,TRUE),
  ('svc-yn-777','YN 777','Other','INR',1000,'IN','high',37,TRUE),
  ('svc-yes-spin','Yes Spin','Other','INR',1000,'IN','high',30,TRUE),
  ('svc-ok-rummy','OK Rummy','Other','INR',1000,'IN','high',43,TRUE),
  ('svc-love-rummy','Love Rummy','Other','INR',1000,'IN','high',67,TRUE),
  ('svc-share-slots','Share Slots','Other','INR',1000,'IN','high',35,TRUE),
  ('svc-hi-rummy','Hi Rummy','Other','INR',1000,'IN','high',90,TRUE),
  ('svc-rani-slots','Rani Slots','Other','INR',1000,'IN','high',82,TRUE),
  ('svc-jaiho-win','Jaiho Win','Other','INR',1000,'IN','high',70,TRUE),
  ('svc-goa-spin','Goa Spin','Other','INR',1000,'IN','medium',94,TRUE),
  ('svc-slots-spin','Slots Spin','Other','INR',1000,'IN','medium',94,TRUE),
  ('svc-mqm-bet','MQM Bet','Other','INR',1000,'IN','high',113,TRUE),
  ('svc-saga-slots','Saga Slots','Other','INR',1000,'IN','high',90,TRUE),
  ('svc-rummy-yono','Rummy Yono','Other','INR',1000,'IN','high',50,TRUE),
  ('svc-abc-rummy','ABC Rummy','Other','INR',1000,'IN','high',81,TRUE),
  ('svc-jaiho-arcade','Jaiho Arcade','Other','INR',1000,'IN','high',40,TRUE),
  ('svc-neta-vip','Neta VIP','Other','INR',1000,'IN','high',26,TRUE),
  ('svc-mwm-bet','MWM Bet','Other','INR',1000,'IN','high',31,TRUE),
  ('svc-en-365','EN 365','Other','INR',1000,'IN','medium',44,TRUE),
  ('svc-101z-app','101Z App','Other','INR',1000,'IN','medium',74,TRUE),
  ('svc-rummy-365','Rummy 365','Other','INR',1000,'IN','high',63,TRUE),
  ('svc-ind-bingo','IND Bingo','Other','INR',1000,'IN','high',27,TRUE),
  ('svc-my-777','My 777','Other','INR',1000,'IN','high',96,TRUE),
  ('svc-bet-213-slots','Bet 213 Slots','Other','INR',1000,'IN','high',32,TRUE),
  ('svc-gogo-rummy','GoGo Rummy','Other','INR',1000,'IN','high',41,TRUE),
  ('svc-789-jackpot','789 Jackpot','Other','INR',1000,'IN','high',107,TRUE),
  ('svc-mdm-bet','MDM Bet','Other','INR',1000,'IN','high',60,TRUE),
  ('svc-spin-lucky','Spin Lucky','Other','INR',1000,'IN','high',113,TRUE),
  ('svc-ind-slots','IND Slots','Other','INR',1000,'IN','medium',69,TRUE),
  ('svc-mkm-bet','MKM Bet','Other','INR',1000,'IN','high',55,TRUE),
  ('svc-yono-maha-games','Yono Maha Games','Other','INR',1000,'IN','high',43,TRUE),
  ('svc-game-rummy','Game Rummy','Other','INR',1000,'IN','medium',49,TRUE),
  ('svc-mbm-bet','MBM Bet','Other','INR',1000,'IN','high',78,TRUE),
  ('svc-jaiho-777','Jaiho 777','Other','INR',1000,'IN','high',67,TRUE),
  ('svc-top-rummy','TOP Rummy','Other','INR',1000,'IN','high',86,TRUE),
  ('svc-spin-777','Spin 777','Other','INR',1000,'IN','high',108,TRUE),
  ('svc-567-slots','567 Slots','Other','INR',1000,'IN','high',46,TRUE),
  ('svc-yono-vip','Yono VIP','Other','INR',1000,'IN','medium',69,TRUE),
  ('svc-yono-slots','Yono Slots','Other','INR',1000,'IN','high',77,TRUE),
  ('svc-yono-arcade','Yono Arcade','Other','INR',1000,'IN','high',110,TRUE),
  ('svc-yono-rummy','Yono Rummy','Other','INR',1000,'IN','high',58,TRUE),
  ('svc-yono-all-games','Yono All Games','Other','INR',1000,'IN','high',25,TRUE),
  ('svc-yono-game','Yono Game','Other','INR',1000,'IN','high',112,TRUE),
  ('svc-yono-games','Yono Games','Other','INR',1000,'IN','high',43,TRUE),
  ('svc-yono-app','Yono App','Other','INR',1000,'IN','medium',29,TRUE),
  ('svc-new-yono-app','New Yono App','Other','INR',1000,'IN','medium',84,TRUE),
  ('svc-all-rummy-apps','All Rummy Apps','Other','INR',1000,'IN','high',37,TRUE),
  ('svc-money-rummy','Money Rummy','Other','INR',1000,'IN','high',33,TRUE),
  ('svc-yn-rummy','YN Rummy','Other','INR',1000,'IN','medium',84,TRUE),
  ('svc-yoyo-slots','Yoyo Slots','Other','INR',1000,'IN','high',70,TRUE),
  ('svc-svip-777','SVIP 777','Other','INR',1000,'IN','high',88,TRUE),
  ('svc-rummy-zip','Rummy Zip','Other','INR',1000,'IN','high',92,TRUE),
  ('svc-diwa-lucky','Diwa Lucky','Other','INR',1000,'IN','high',100,TRUE),
  ('svc-diwa-ace','Diwa Ace','Other','INR',1000,'IN','high',25,TRUE),
  ('svc-diwa-king','Diwa King','Other','INR',1000,'IN','high',35,TRUE),
  ('svc-diwa-play','Diwa Play','Other','INR',1000,'IN','high',50,TRUE),
  ('svc-diwa-bet','Diwa Bet','Other','INR',1000,'IN','high',43,TRUE),
  ('svc-diwa-spin','Diwa Spin','Other','INR',1000,'IN','high',28,TRUE),
  ('svc-diwa-rummy','Diwa Rummy','Other','INR',1000,'IN','high',96,TRUE),
  ('svc-diwa-club','Diwa Club','Other','INR',1000,'IN','high',80,TRUE),
  ('svc-diwa-91','Diwa 91','Other','INR',1000,'IN','high',60,TRUE),
  ('svc-diwa-gold','Diwa Gold','Other','INR',1000,'IN','high',68,TRUE),
  ('svc-jeet-spin','Jeet Spin','Other','INR',1000,'IN','high',27,TRUE),
  ('svc-all-diwa-apps','All Diwa Apps','Other','INR',1000,'IN','high',66,TRUE),
  ('svc-pp-777','PP 777','Other','INR',1000,'IN','high',40,TRUE),
  ('svc-holy-rummy','Holy Rummy','Other','INR',1000,'IN','high',33,TRUE),
  ('svc-teen-patti-master','Teen Patti Master','Other','INR',1000,'IN','high',106,TRUE),
  ('svc-ind-vip','Ind Vip','Other','INR',1000,'IN','high',83,TRUE),
  ('svc-rumble-rummy-77','Rumble Rummy 77','Other','INR',1000,'IN','high',95,TRUE),
  ('svc-yono-rumble-rummy','Yono Rumble Rummy','Other','INR',1000,'IN','high',28,TRUE),
  ('svc-bolly-game','Bolly Game','Other','INR',1000,'IN','medium',29,TRUE),
  ('svc-t989','T989','Other','INR',1000,'IN','high',86,TRUE),
  ('svc-rummy-mate','Rummy Mate','Other','INR',1000,'IN','high',46,TRUE),
  ('svc-rummy-gold','Rummy GOLD','Other','INR',1000,'IN','medium',59,TRUE),
  ('svc-tycoon','Tycoon','Other','INR',1000,'IN','high',62,TRUE),
  ('svc-k9','K9','Other','INR',1000,'IN','high',96,TRUE),
  ('svc-mmy','MMY','Other','INR',1000,'IN','high',101,TRUE),
  ('svc-bdg-game','BDG Game','Other','INR',1000,'IN','high',60,TRUE),
  ('svc-new-66-lotry','NEW 66 lotry','Other','INR',1000,'IN','high',42,TRUE),
  ('svc-ww9','Ww9','Other','INR',1000,'IN','medium',29,TRUE),
  ('svc-goplay11','Goplay11','Other','INR',1000,'IN','high',76,TRUE),
  ('svc-win-03','Win 03','Other','INR',1000,'IN','high',92,TRUE),
  ('svc-woho-game','Woho Game','Other','INR',1000,'IN','high',68,TRUE),
  ('svc-yono-slot','Yono Slot','Other','INR',1000,'IN','high',110,TRUE),
  ('svc-come11','Come11','Other','INR',1000,'IN','high',30,TRUE),
  ('svc-kaliwins','KaliWins','Other','INR',1000,'IN','high',28,TRUE),
  ('svc-rummy-holly','RUMMY HOLLY','Other','INR',1000,'IN','high',71,TRUE),
  ('svc-rummy-nabob','rummy nabob','Other','INR',1000,'IN','medium',59,TRUE),
  ('svc-rummy-ola','RUMMY OLA','Other','INR',1000,'IN','medium',39,TRUE),
  ('svc-diva-ace','Diva ace','Other','INR',1000,'IN','high',58,TRUE),
  ('svc-diva-lucky','Diva Lucky','Other','INR',1000,'IN','high',113,TRUE),
  ('svc-diva-king','Diva King','Other','INR',1000,'IN','high',78,TRUE),
  ('svc-diva-x','Diva X','Other','INR',1000,'IN','medium',69,TRUE),
  ('svc-diva-top','Diva Top','Other','INR',1000,'IN','medium',24,TRUE),
  ('svc-divavip','DivaVIP','Other','INR',1000,'IN','high',81,TRUE),
  ('svc-diva-game','Diva Game','Other','INR',1000,'IN','high',53,TRUE),
  ('svc-diva-slots','Diva Slots','Other','INR',1000,'IN','high',38,TRUE),
  ('svc-diva-777','Diva 777','Other','INR',1000,'IN','high',36,TRUE),
  ('svc-jai-ho-slots','JAI HO SLOTS','Other','INR',1000,'IN','high',68,TRUE),
  ('svc-slot-spin','Slot Spin','Other','INR',1000,'IN','high',85,TRUE),
  ('svc-diva-2026','Diva 2026','Other','INR',1000,'IN','high',101,TRUE),
  ('svc-teen-patti-gold','Teen Patti Gold','Other','INR',1000,'IN','high',32,TRUE),
  ('svc-rummy-wealth','Rummy Wealth','Other','INR',1000,'IN','high',112,TRUE),
  ('svc-rummy-modern','Rummy Modern','Other','INR',1000,'IN','high',46,TRUE),
  ('svc-rummy-all-app','Rummy All App','Other','INR',1000,'IN','high',62,TRUE),
  ('svc-ak777','AK777','Other','INR',1000,'IN','high',111,TRUE),
  ('svc-rummy-ares','Rummy Ares','Other','INR',1000,'IN','medium',94,TRUE),
  ('svc-11-winner-apk','11 Winner APK','Other','INR',1000,'IN','high',41,TRUE),
  ('svc-all-rummy-app','All Rummy App','Other','INR',1000,'IN','high',36,TRUE),
  ('svc-rummy-new-app','Rummy New App','Other','INR',1000,'IN','high',97,TRUE),
  ('svc-colour-trading','Colour Trading','Other','INR',1000,'IN','high',92,TRUE),
  ('svc-prosafe-bet','Prosafe Bet','Other','INR',1000,'IN','high',30,TRUE),
  ('svc-msm-bet','MSM Bet','Other','INR',1000,'IN','high',93,TRUE),
  ('svc-365-jeet','365 Jeet','Other','INR',1000,'IN','high',51,TRUE),
  ('svc-rk-ludo','RK Ludo','Other','INR',1000,'IN','high',108,TRUE),
  ('svc-gogo-anime','Gogo Anime','Other','INR',1000,'IN','medium',109,TRUE),
  ('svc-spin-yono','Spin Yono','Other','INR',1000,'IN','high',88,TRUE),
  ('svc-game-3f','Game 3f','Other','INR',1000,'IN','high',62,TRUE),
  ('svc-download-svip','Download Svip','Other','INR',1000,'IN','high',77,TRUE),
  ('svc-kal-win','KAL WIN','Other','INR',1000,'IN','medium',49,TRUE),
  ('svc-rummy-sultan','Rummy Sultan','Other','INR',1000,'IN','medium',64,TRUE),
  ('svc-new-rummy-app','New Rummy App','Other','INR',1000,'IN','high',37,TRUE),
  ('svc-1a-game','1a Game','Other','INR',1000,'IN','high',37,TRUE),
  ('svc-8-game-app','8 Game App','Other','INR',1000,'IN','high',83,TRUE),
  ('svc-slots-777','Slots 777','Other','INR',1000,'IN','high',111,TRUE),
  ('svc-slot-guru','Slot Guru','Other','INR',1000,'IN','high',72,TRUE),
  ('svc-rummy-black','Rummy Black','Other','INR',1000,'IN','high',98,TRUE),
  ('svc-teenpatti-happy','TeenPatti Happy','Other','INR',1000,'IN','medium',109,TRUE),
  ('svc-rummy-master','Rummy Master','Other','INR',1000,'IN','high',95,TRUE),
  ('svc-yono-rummy-2026','Yono Rummy 2026','Other','INR',1000,'IN','high',63,TRUE),
  ('svc-all-yono-apk','All Yono Apk','Other','INR',1000,'IN','high',46,TRUE),
  ('svc-casino-game','CASINO GAME','Other','INR',1000,'IN','high',38,TRUE),
  ('svc-yono-games-list','Yono Games List','Other','INR',1000,'IN','high',48,TRUE),
  ('svc-777-rummy','777 Rummy','Other','INR',1000,'IN','high',86,TRUE),
  ('svc-rummy-vip-apk','Rummy Vip APK','Other','INR',1000,'IN','medium',109,TRUE),
  ('svc-download-rummy-ludo','Download Rummy Ludo','Other','INR',1000,'IN','high',26,TRUE),
  ('svc-crush-spin','Crush Spin','Other','INR',1000,'IN','high',48,TRUE),
  ('svc-abc-vip','ABC VIP','Other','INR',1000,'IN','high',36,TRUE),
  ('svc-rummy-333','Rummy 333','Other','INR',1000,'IN','high',96,TRUE),
  ('svc-best-yono-app','Best Yono App','Other','INR',1000,'IN','medium',34,TRUE),
  ('svc-best-yono','Best Yono','Other','INR',1000,'IN','high',80,TRUE),
  ('svc-pop-slots','POP Slots','Other','INR',1000,'IN','high',105,TRUE),
  ('svc-download-yono-rummy','Download Yono Rummy','Other','INR',1000,'IN','high',57,TRUE),
  ('svc-download-lcg-bet','DOWNLOAD LCG BET','Other','INR',1000,'IN','medium',79,TRUE),
  ('svc-3-patti-master','3 Patti Master','Other','INR',1000,'IN','high',41,TRUE),
  ('svc-teen-patti-bliss','Teen Patti Bliss','Other','INR',1000,'IN','high',37,TRUE),
  ('svc-navo-slots','Navo Slots','Other','INR',1000,'IN','medium',84,TRUE),
  ('svc-jaiclub-game','Jaiclub GAME','Other','INR',1000,'IN','high',87,TRUE),
  ('svc-sxripl-game','SXRIPL GAME','Other','INR',1000,'IN','high',101,TRUE),
  ('svc-rummy-loot','Rummy Loot','Other','INR',1000,'IN','high',107,TRUE),
  ('svc-all-vv5-game','ALL VV5 GAME','Other','INR',1000,'IN','high',110,TRUE),
  ('svc-crown-rummy','Crown Rummy','Other','INR',1000,'IN','high',78,TRUE),
  ('svc-teenpatti-bazaar','Teenpatti Bazaar','Other','INR',1000,'IN','high',66,TRUE),
  ('svc-5177-win','5177 Win','Other','INR',1000,'IN','medium',39,TRUE),
  ('svc-yono-arcarde','Yono Arcarde','Other','INR',1000,'IN','medium',44,TRUE),
  ('svc-rummy-good','Rummy Good','Other','INR',1000,'IN','medium',94,TRUE),
  ('svc-bet-11','Bet 11','Other','INR',1000,'IN','high',92,TRUE),
  ('svc-ayuipl-game','AYUIPL GAME','Other','INR',1000,'IN','high',73,TRUE),
  ('svc-download-rummy-365','Download Rummy 365','Other','INR',1000,'IN','high',98,TRUE),
  ('svc-rummy-777','Rummy 777','Other','INR',1000,'IN','high',108,TRUE),
  ('svc-koko-slots','KOKO SLOTS','Other','INR',1000,'IN','high',78,TRUE),
  ('svc-raja-game-download','Raja Game Download','Other','INR',1000,'IN','high',50,TRUE),
  ('svc-yono-yoyo-slots','Yono Yoyo Slots','Other','INR',1000,'IN','high',82,TRUE),
  ('svc-gg9-android-app','Gg9 Android App','Other','INR',1000,'IN','medium',109,TRUE),
  ('svc-frenzy-winner','Frenzy Winner','Other','INR',1000,'IN','medium',74,TRUE),
  ('svc-en-365-games','En 365 Games','Other','INR',1000,'IN','high',26,TRUE),
  ('svc-9game-apk','9Game Apk','Other','INR',1000,'IN','high',58,TRUE),
  ('svc-diwa-slot','Diwa Slot','Other','INR',1000,'IN','high',38,TRUE),
  ('svc-namaste-teenpatti-apk','Namaste Teenpatti Apk','Other','INR',1000,'IN','high',77,TRUE),
  ('svc-all-yono-slots','All Yono Slots','Other','INR',1000,'IN','high',71,TRUE),
  ('svc-3-patti-hot','3 Patti Hot','Other','INR',1000,'IN','medium',104,TRUE),
  ('svc-21-game-download','21 Game Download','Other','INR',1000,'IN','high',107,TRUE),
  ('svc-rummy-grand','Rummy Grand','Other','INR',1000,'IN','high',55,TRUE)
),
renamed AS (
  UPDATE services s
  SET name = s.name || ' [legacy:' || s.id || ']'
  FROM new_services n
  WHERE s.id NOT LIKE 'svc-%' AND s.name = n.name
  RETURNING s.id
)
INSERT INTO services
  (id,name,category,currency,price_paise,country,availability,stock,active)
SELECT id,name,category,currency,price_paise,country,availability,stock,active
FROM new_services
ON CONFLICT (id) DO UPDATE SET
  name=EXCLUDED.name,
  category=EXCLUDED.category,
  currency=EXCLUDED.currency,
  price_paise=EXCLUDED.price_paise,
  country=EXCLUDED.country,
  availability=EXCLUDED.availability,
  stock=EXCLUDED.stock,
  active=TRUE,
  updated_at=NOW();

INSERT INTO service_provider_routes (service_id,provider_id,priority,active)
VALUES
  ('svc-yono-bonus-51','provider-mock',10,TRUE),
  ('svc-joy-rummy','provider-mock',10,TRUE),
  ('svc-ind-rummy','provider-mock',10,TRUE),
  ('svc-inr-rummy','provider-mock',10,TRUE),
  ('svc-rumble-rummy','provider-mock',10,TRUE),
  ('svc-bingo-101','provider-mock',10,TRUE),
  ('svc-spin-101','provider-mock',10,TRUE),
  ('svc-diwa-top','provider-mock',10,TRUE),
  ('svc-jaiho-slots','provider-mock',10,TRUE),
  ('svc-rummy-91','provider-mock',10,TRUE),
  ('svc-max-rummy','provider-mock',10,TRUE),
  ('svc-gold-rummy','provider-mock',10,TRUE),
  ('svc-win-rummy','provider-mock',10,TRUE),
  ('svc-diwa-x','provider-mock',10,TRUE),
  ('svc-jaiho-rummy','provider-mock',10,TRUE),
  ('svc-jaiho-91','provider-mock',10,TRUE),
  ('svc-diwa-win','provider-mock',10,TRUE),
  ('svc-maha-games','provider-mock',10,TRUE),
  ('svc-jaiho-777-vip','provider-mock',10,TRUE),
  ('svc-rummy-888','provider-mock',10,TRUE),
  ('svc-dhan-game','provider-mock',10,TRUE),
  ('svc-diwa-game','provider-mock',10,TRUE),
  ('svc-diwa-vip','provider-mock',10,TRUE),
  ('svc-ind-club','provider-mock',10,TRUE),
  ('svc-all-yono-games','provider-mock',10,TRUE),
  ('svc-diwa-slots','provider-mock',10,TRUE),
  ('svc-diwa-777','provider-mock',10,TRUE),
  ('svc-spin-crush','provider-mock',10,TRUE),
  ('svc-spin-winner','provider-mock',10,TRUE),
  ('svc-spin-gold','provider-mock',10,TRUE),
  ('svc-slots-winner','provider-mock',10,TRUE),
  ('svc-rummy-ludo','provider-mock',10,TRUE),
  ('svc-jaiho-spin','provider-mock',10,TRUE),
  ('svc-yono-777','provider-mock',10,TRUE),
  ('svc-rummy-77','provider-mock',10,TRUE),
  ('svc-777-game','provider-mock',10,TRUE),
  ('svc-club-inr','provider-mock',10,TRUE),
  ('svc-winzo-rummy','provider-mock',10,TRUE),
  ('svc-rummy-app','provider-mock',10,TRUE),
  ('svc-ever-777','provider-mock',10,TRUE),
  ('svc-inr-slots','provider-mock',10,TRUE),
  ('svc-good-slots','provider-mock',10,TRUE),
  ('svc-boss-rummy','provider-mock',10,TRUE),
  ('svc-hindi-777','provider-mock',10,TRUE),
  ('svc-yn-777','provider-mock',10,TRUE),
  ('svc-yes-spin','provider-mock',10,TRUE),
  ('svc-ok-rummy','provider-mock',10,TRUE),
  ('svc-love-rummy','provider-mock',10,TRUE),
  ('svc-share-slots','provider-mock',10,TRUE),
  ('svc-hi-rummy','provider-mock',10,TRUE),
  ('svc-rani-slots','provider-mock',10,TRUE),
  ('svc-jaiho-win','provider-mock',10,TRUE),
  ('svc-goa-spin','provider-mock',10,TRUE),
  ('svc-slots-spin','provider-mock',10,TRUE),
  ('svc-mqm-bet','provider-mock',10,TRUE),
  ('svc-saga-slots','provider-mock',10,TRUE),
  ('svc-rummy-yono','provider-mock',10,TRUE),
  ('svc-abc-rummy','provider-mock',10,TRUE),
  ('svc-jaiho-arcade','provider-mock',10,TRUE),
  ('svc-neta-vip','provider-mock',10,TRUE),
  ('svc-mwm-bet','provider-mock',10,TRUE),
  ('svc-en-365','provider-mock',10,TRUE),
  ('svc-101z-app','provider-mock',10,TRUE),
  ('svc-rummy-365','provider-mock',10,TRUE),
  ('svc-ind-bingo','provider-mock',10,TRUE),
  ('svc-my-777','provider-mock',10,TRUE),
  ('svc-bet-213-slots','provider-mock',10,TRUE),
  ('svc-gogo-rummy','provider-mock',10,TRUE),
  ('svc-789-jackpot','provider-mock',10,TRUE),
  ('svc-mdm-bet','provider-mock',10,TRUE),
  ('svc-spin-lucky','provider-mock',10,TRUE),
  ('svc-ind-slots','provider-mock',10,TRUE),
  ('svc-mkm-bet','provider-mock',10,TRUE),
  ('svc-yono-maha-games','provider-mock',10,TRUE),
  ('svc-game-rummy','provider-mock',10,TRUE),
  ('svc-mbm-bet','provider-mock',10,TRUE),
  ('svc-jaiho-777','provider-mock',10,TRUE),
  ('svc-top-rummy','provider-mock',10,TRUE),
  ('svc-spin-777','provider-mock',10,TRUE),
  ('svc-567-slots','provider-mock',10,TRUE),
  ('svc-yono-vip','provider-mock',10,TRUE),
  ('svc-yono-slots','provider-mock',10,TRUE),
  ('svc-yono-arcade','provider-mock',10,TRUE),
  ('svc-yono-rummy','provider-mock',10,TRUE),
  ('svc-yono-all-games','provider-mock',10,TRUE),
  ('svc-yono-game','provider-mock',10,TRUE),
  ('svc-yono-games','provider-mock',10,TRUE),
  ('svc-yono-app','provider-mock',10,TRUE),
  ('svc-new-yono-app','provider-mock',10,TRUE),
  ('svc-all-rummy-apps','provider-mock',10,TRUE),
  ('svc-money-rummy','provider-mock',10,TRUE),
  ('svc-yn-rummy','provider-mock',10,TRUE),
  ('svc-yoyo-slots','provider-mock',10,TRUE),
  ('svc-svip-777','provider-mock',10,TRUE),
  ('svc-rummy-zip','provider-mock',10,TRUE),
  ('svc-diwa-lucky','provider-mock',10,TRUE),
  ('svc-diwa-ace','provider-mock',10,TRUE),
  ('svc-diwa-king','provider-mock',10,TRUE),
  ('svc-diwa-play','provider-mock',10,TRUE),
  ('svc-diwa-bet','provider-mock',10,TRUE),
  ('svc-diwa-spin','provider-mock',10,TRUE),
  ('svc-diwa-rummy','provider-mock',10,TRUE),
  ('svc-diwa-club','provider-mock',10,TRUE),
  ('svc-diwa-91','provider-mock',10,TRUE),
  ('svc-diwa-gold','provider-mock',10,TRUE),
  ('svc-jeet-spin','provider-mock',10,TRUE),
  ('svc-all-diwa-apps','provider-mock',10,TRUE),
  ('svc-pp-777','provider-mock',10,TRUE),
  ('svc-holy-rummy','provider-mock',10,TRUE),
  ('svc-teen-patti-master','provider-mock',10,TRUE),
  ('svc-ind-vip','provider-mock',10,TRUE),
  ('svc-rumble-rummy-77','provider-mock',10,TRUE),
  ('svc-yono-rumble-rummy','provider-mock',10,TRUE),
  ('svc-bolly-game','provider-mock',10,TRUE),
  ('svc-t989','provider-mock',10,TRUE),
  ('svc-rummy-mate','provider-mock',10,TRUE),
  ('svc-rummy-gold','provider-mock',10,TRUE),
  ('svc-tycoon','provider-mock',10,TRUE),
  ('svc-k9','provider-mock',10,TRUE),
  ('svc-mmy','provider-mock',10,TRUE),
  ('svc-bdg-game','provider-mock',10,TRUE),
  ('svc-new-66-lotry','provider-mock',10,TRUE),
  ('svc-ww9','provider-mock',10,TRUE),
  ('svc-goplay11','provider-mock',10,TRUE),
  ('svc-win-03','provider-mock',10,TRUE),
  ('svc-woho-game','provider-mock',10,TRUE),
  ('svc-yono-slot','provider-mock',10,TRUE),
  ('svc-come11','provider-mock',10,TRUE),
  ('svc-kaliwins','provider-mock',10,TRUE),
  ('svc-rummy-holly','provider-mock',10,TRUE),
  ('svc-rummy-nabob','provider-mock',10,TRUE),
  ('svc-rummy-ola','provider-mock',10,TRUE),
  ('svc-diva-ace','provider-mock',10,TRUE),
  ('svc-diva-lucky','provider-mock',10,TRUE),
  ('svc-diva-king','provider-mock',10,TRUE),
  ('svc-diva-x','provider-mock',10,TRUE),
  ('svc-diva-top','provider-mock',10,TRUE),
  ('svc-divavip','provider-mock',10,TRUE),
  ('svc-diva-game','provider-mock',10,TRUE),
  ('svc-diva-slots','provider-mock',10,TRUE),
  ('svc-diva-777','provider-mock',10,TRUE),
  ('svc-jai-ho-slots','provider-mock',10,TRUE),
  ('svc-slot-spin','provider-mock',10,TRUE),
  ('svc-diva-2026','provider-mock',10,TRUE),
  ('svc-teen-patti-gold','provider-mock',10,TRUE),
  ('svc-rummy-wealth','provider-mock',10,TRUE),
  ('svc-rummy-modern','provider-mock',10,TRUE),
  ('svc-rummy-all-app','provider-mock',10,TRUE),
  ('svc-ak777','provider-mock',10,TRUE),
  ('svc-rummy-ares','provider-mock',10,TRUE),
  ('svc-11-winner-apk','provider-mock',10,TRUE),
  ('svc-all-rummy-app','provider-mock',10,TRUE),
  ('svc-rummy-new-app','provider-mock',10,TRUE),
  ('svc-colour-trading','provider-mock',10,TRUE),
  ('svc-prosafe-bet','provider-mock',10,TRUE),
  ('svc-msm-bet','provider-mock',10,TRUE),
  ('svc-365-jeet','provider-mock',10,TRUE),
  ('svc-rk-ludo','provider-mock',10,TRUE),
  ('svc-gogo-anime','provider-mock',10,TRUE),
  ('svc-spin-yono','provider-mock',10,TRUE),
  ('svc-game-3f','provider-mock',10,TRUE),
  ('svc-download-svip','provider-mock',10,TRUE),
  ('svc-kal-win','provider-mock',10,TRUE),
  ('svc-rummy-sultan','provider-mock',10,TRUE),
  ('svc-new-rummy-app','provider-mock',10,TRUE),
  ('svc-1a-game','provider-mock',10,TRUE),
  ('svc-8-game-app','provider-mock',10,TRUE),
  ('svc-slots-777','provider-mock',10,TRUE),
  ('svc-slot-guru','provider-mock',10,TRUE),
  ('svc-rummy-black','provider-mock',10,TRUE),
  ('svc-teenpatti-happy','provider-mock',10,TRUE),
  ('svc-rummy-master','provider-mock',10,TRUE),
  ('svc-yono-rummy-2026','provider-mock',10,TRUE),
  ('svc-all-yono-apk','provider-mock',10,TRUE),
  ('svc-casino-game','provider-mock',10,TRUE),
  ('svc-yono-games-list','provider-mock',10,TRUE),
  ('svc-777-rummy','provider-mock',10,TRUE),
  ('svc-rummy-vip-apk','provider-mock',10,TRUE),
  ('svc-download-rummy-ludo','provider-mock',10,TRUE),
  ('svc-crush-spin','provider-mock',10,TRUE),
  ('svc-abc-vip','provider-mock',10,TRUE),
  ('svc-rummy-333','provider-mock',10,TRUE),
  ('svc-best-yono-app','provider-mock',10,TRUE),
  ('svc-best-yono','provider-mock',10,TRUE),
  ('svc-pop-slots','provider-mock',10,TRUE),
  ('svc-download-yono-rummy','provider-mock',10,TRUE),
  ('svc-download-lcg-bet','provider-mock',10,TRUE),
  ('svc-3-patti-master','provider-mock',10,TRUE),
  ('svc-teen-patti-bliss','provider-mock',10,TRUE),
  ('svc-navo-slots','provider-mock',10,TRUE),
  ('svc-jaiclub-game','provider-mock',10,TRUE),
  ('svc-sxripl-game','provider-mock',10,TRUE),
  ('svc-rummy-loot','provider-mock',10,TRUE),
  ('svc-all-vv5-game','provider-mock',10,TRUE),
  ('svc-crown-rummy','provider-mock',10,TRUE),
  ('svc-teenpatti-bazaar','provider-mock',10,TRUE),
  ('svc-5177-win','provider-mock',10,TRUE),
  ('svc-yono-arcarde','provider-mock',10,TRUE),
  ('svc-rummy-good','provider-mock',10,TRUE),
  ('svc-bet-11','provider-mock',10,TRUE),
  ('svc-ayuipl-game','provider-mock',10,TRUE),
  ('svc-download-rummy-365','provider-mock',10,TRUE),
  ('svc-rummy-777','provider-mock',10,TRUE),
  ('svc-koko-slots','provider-mock',10,TRUE),
  ('svc-raja-game-download','provider-mock',10,TRUE),
  ('svc-yono-yoyo-slots','provider-mock',10,TRUE),
  ('svc-gg9-android-app','provider-mock',10,TRUE),
  ('svc-frenzy-winner','provider-mock',10,TRUE),
  ('svc-en-365-games','provider-mock',10,TRUE),
  ('svc-9game-apk','provider-mock',10,TRUE),
  ('svc-diwa-slot','provider-mock',10,TRUE),
  ('svc-namaste-teenpatti-apk','provider-mock',10,TRUE),
  ('svc-all-yono-slots','provider-mock',10,TRUE),
  ('svc-3-patti-hot','provider-mock',10,TRUE),
  ('svc-21-game-download','provider-mock',10,TRUE),
  ('svc-rummy-grand','provider-mock',10,TRUE)
ON CONFLICT (service_id,provider_id) DO UPDATE SET
  active=TRUE,
  priority=EXCLUDED.priority;

INSERT INTO schema_migrations(version)
VALUES ('032_service_catalog_v2')
ON CONFLICT DO NOTHING;

COMMIT;
